/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2023 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/


const char html_menu_setup[] PROGMEM =
    "<script>"
        "var showLogout = _SHOW_LOGOUT_;"
        "document.onreadystatechange = function() {"
            "if (document.readyState === 'complete') {"
                "if (showLogout == 0) {"
                    "var element = document.getElementById('logout');"
                    "element.parentNode.removeChild(element);"
                "}"
            "}"
        "}"
    "</script>"
        "<div style='text-align:center;'>"
            "<h2>_TXT_SETUP_PAGE_</h2>"
        "</div>"
        "<div>"
            "<form action='/timers' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<circle cx='12' cy='12' r='9'/>"
                            "<path d='M12 7v5l3.5 2'/>"
                        "</svg>"
                    "</span>"
                    "Zeitpl&#228;ne"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/devices' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71'/>"
                            "<path d='M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71'/>"
                        "</svg>"
                    "</span>"
                    "Ger&#228;te"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/mqtt' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M4 11a9 9 0 0 1 9 9'/>"
                            "<path d='M4 4a16 16 0 0 1 16 16'/>"
                            "<circle cx='5' cy='19' r='1'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_MQTT_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/wifi' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M5 12.55a11 11 0 0 1 14.08 0'/>"
                            "<path d='M1.42 9a16 16 0 0 1 21.16 0'/>"
                            "<path d='M8.53 16.11a6 6 0 0 1 6.95 0'/>"
                            "<circle cx='12' cy='20' r='1'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_WIFI_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/unit' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<rect x='2' y='4' width='20' height='9' rx='2'/>"
                            "<path d='M6 17h.01M10 17h.01M14 17h.01M18 17h.01M6 20h12'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_UNIT_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/others' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<line x1='4' y1='21' x2='4' y2='14'/>"
                            "<line x1='4' y1='10' x2='4' y2='3'/>"
                            "<line x1='12' y1='21' x2='12' y2='12'/>"
                            "<line x1='12' y1='8' x2='12' y2='3'/>"
                            "<line x1='20' y1='21' x2='20' y2='16'/>"
                            "<line x1='20' y1='12' x2='20' y2='3'/>"
                            "<line x1='1' y1='14' x2='7' y2='14'/>"
                            "<line x1='9' y1='8' x2='15' y2='8'/>"
                            "<line x1='17' y1='16' x2='23' y2='16'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_OTHERS_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/status' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M22 12h-4l-3 9L9 3l-3 9H2'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_STATUS_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/upgrade' method='get'>"
                "<button class='mbtn'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4'/>"
                            "<path d='M17 8l-5-5-5 5'/>"
                            "<path d='M12 3v12'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_FW_UPGRADE_"
                "</button>"
            "</form>"
        "</div>"
        "<div>"
            "<form action='/' method='get'>"
                "<button type='submit' name='REBOOT' class='mbtn danger'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M23 4v6h-6'/>"
                            "<path d='M20.49 15a9 9 0 1 1-2.12-9.36L23 10'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_REBOOT_"
                "</button>"
            "</form>"
       "</div>"
        "<div>"
            "<form onsubmit=\"return confirm('_TXT_RESET_CONFIRM_');\" method='post'>"
                "<button type='submit' name='RESET' class='mbtn danger'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M3 6h18'/>"
                            "<path d='M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6'/>"
                            "<path d='M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_RESET_"
                "</button>"
            "</form>"
        "</div>"
        "<div id='logout'>"
            "<form action='/login?LOGOUT=YES' method='post'>"
                "<button type='submit' name='Logout' class='mbtn danger'>"
                    "<span class='ic'>"
                        "<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                            "<path d='M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4'/>"
                            "<path d='M16 17l5-5-5-5'/>"
                            "<path d='M21 12H9'/>"
                        "</svg>"
                    "</span>"
                    "_TXT_LOGOUT_"
                "</button>"
            "</form>"
        "</div>"
        "<p>"
		    "<form action='/' method='get'>"
                "<button class='back'>_TXT_BACK_</button>"
            "</form>"
        "</p>"
;
