/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2019 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

const char html_css[] PROGMEM =
        ":root {"
            "--bg: #f2f5fa;"
            "--card: #ffffff;"
            "--card2: #eef2f8;"
            "--text: #0f172a;"
            "--muted: #64748b;"
            "--border: #dfe6f0;"
            "--accent: #2563eb;"
            "--accent2: #06b6d4;"
            "--accent-soft: rgba(37,99,235,.12);"
            "--ok: #059669;"
            "--ok2: #10b981;"
            "--ok-soft: rgba(5,150,105,.12);"
            "--danger: #dc2626;"
            "--danger2: #ef4444;"
            "--danger-soft: rgba(220,38,38,.1);"
            "--warn: #d97706;"
            "--shadow: 0 6px 20px rgba(15,23,42,.07);"
            "--ring: rgba(37,99,235,.30);"
        "}"
        "@media (prefers-color-scheme: dark) {"
            ":root:not([data-theme='light']) {"
                "--bg: #0b1120;"
                "--card: #151e33;"
                "--card2: #1d2946;"
                "--text: #e6ecf5;"
                "--muted: #8fa1bd;"
                "--border: #263351;"
                "--accent: #3b82f6;"
                "--accent2: #22d3ee;"
                "--accent-soft: rgba(59,130,246,.16);"
                "--ok: #34d399;"
                "--ok2: #10b981;"
                "--ok-soft: rgba(52,211,153,.14);"
                "--danger: #f87171;"
                "--danger2: #ef4444;"
                "--danger-soft: rgba(248,113,113,.12);"
                "--warn: #fbbf24;"
                "--shadow: 0 10px 30px rgba(0,0,0,.35);"
                "--ring: rgba(59,130,246,.40);"
            "}"
        "}"
        ":root[data-theme='dark'] {"
            "--bg: #0b1120;"
            "--card: #151e33;"
            "--card2: #1d2946;"
            "--text: #e6ecf5;"
            "--muted: #8fa1bd;"
            "--border: #263351;"
            "--accent: #3b82f6;"
            "--accent2: #22d3ee;"
            "--accent-soft: rgba(59,130,246,.16);"
            "--ok: #34d399;"
            "--ok2: #10b981;"
            "--ok-soft: rgba(52,211,153,.14);"
            "--danger: #f87171;"
            "--danger2: #ef4444;"
            "--danger-soft: rgba(248,113,113,.12);"
            "--warn: #fbbf24;"
            "--shadow: 0 10px 30px rgba(0,0,0,.35);"
            "--ring: rgba(59,130,246,.40);"
        "}"
        "* {"
            "box-sizing: border-box;"
            "font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;"
        "}"
        "body {"
            "margin: 0;"
            "padding: 22px 14px 40px;"
            "min-height: 100vh;"
            "text-align: center;"
            "color: var(--text);"
            "background: radial-gradient(900px 420px at 50% -120px, var(--accent-soft), transparent 60%), var(--bg);"
        "}"
        ".main {"
            "display: inline-block;"
            "text-align: left;"
            "width: 100%;"
            "max-width: 440px;"
        "}"
        /* top bar with logo + unit name */
        ".top {"
            "display: flex;"
            "align-items: center;"
            "justify-content: center;"
            "gap: 12px;"
            "margin: 4px 0 18px;"
            "position: relative;"
        "}"
        /* settings shortcut top right; only shown on the control page (issue #7) */
        ".gearlink {"
            "position: absolute;"
            "right: 0;"
            "top: 50%;"
            "transform: translateY(-50%);"
            "display: none;"
            "color: var(--muted);"
            "opacity: .7;"
            "line-height: 0;"
            "padding: 6px;"
        "}"
        ".gearlink:hover {"
            "opacity: 1;"
        "}"
        ".mark {"
            "display: inline-flex;"
            "align-items: center;"
            "justify-content: center;"
            "width: 44px;"
            "height: 44px;"
            "border-radius: 13px;"
            "color: #fff;"
            "background: linear-gradient(135deg, var(--accent), var(--accent2));"
            "box-shadow: 0 4px 14px var(--ring);"
            "flex: none;"
        "}"
        ".tt h3 {"
            "margin: 0;"
            "font-size: 1.25rem;"
            "font-weight: 700;"
            "letter-spacing: .01em;"
        "}"
        ".tt .app {"
            "display: block;"
            "font-size: .72rem;"
            "font-weight: 600;"
            "letter-spacing: .14em;"
            "text-transform: uppercase;"
            "color: var(--muted);"
        "}"
        "h2 {"
            "text-align: center;"
            "font-size: .95rem;"
            "font-weight: 600;"
            "letter-spacing: .06em;"
            "text-transform: uppercase;"
            "color: var(--muted);"
            "margin: 4px 0 16px;"
        "}"
        "p {"
            "margin: .8em 0;"
        "}"
        /* cards */
        "fieldset {"
            "background: var(--card);"
            "border: 1px solid var(--border);"
            "border-radius: 16px;"
            "padding: 14px 16px 16px;"
            "margin: 0 0 14px;"
            "box-shadow: var(--shadow);"
            "min-inline-size: 0;"
            "min-width: 0;"
        "}"
        "legend {"
            "padding: 3px 12px;"
            "font-size: .72rem;"
            "font-weight: 700;"
            "letter-spacing: .08em;"
            "text-transform: uppercase;"
            "color: var(--accent);"
            "background: var(--accent-soft);"
            "border-radius: 999px;"
        "}"
        "legend b {"
            "font-weight: 700;"
        "}"
        /* form labels: p > b acts as field label */
        "p > b {"
            "display: block;"
            "font-size: .8rem;"
            "font-weight: 600;"
            "color: var(--muted);"
            "margin-bottom: 4px;"
        "}"
        /* inputs */
        "input, select, textarea {"
            "width: 100%;"
            "padding: 10px 12px;"
            "font-size: 1rem;"
            "color: var(--text);"
            "background: var(--card2);"
            "border: 1px solid var(--border);"
            "border-radius: 10px;"
            "outline: none;"
            "transition: border-color .15s, box-shadow .15s;"
        "}"
        "input:focus, select:focus, textarea:focus {"
            "border-color: var(--accent);"
            "box-shadow: 0 0 0 3px var(--ring);"
        "}"
        "input[type=checkbox],"
        "input[type=radio] {"
            "width: 1em;"
            "margin-right: 6px;"
            "vertical-align: -1px;"
        "}"
        "input[type=file] {"
            "font-size: .9rem;"
        "}"
        "select {"
            "appearance: none;"
            "-webkit-appearance: none;"
            "cursor: pointer;"
            "background-image: linear-gradient(45deg, transparent 50%, var(--muted) 50%), linear-gradient(135deg, var(--muted) 50%, transparent 50%);"
            "background-position: calc(100% - 18px) 55%, calc(100% - 13px) 55%;"
            "background-size: 5px 5px;"
            "background-repeat: no-repeat;"
            "padding-right: 34px;"
        "}"
        "textarea {"
            "resize: vertical;"
            "height: 60px;"
            "overflow: auto;"
            "font-size: .85rem;"
        "}"
        "td {"
            "padding: 0px;"
        "}"
        "a {"
            "color: var(--accent);"
            "text-decoration: none;"
        "}"
        /* buttons */
        "button {"
            "display: flex;"
            "align-items: center;"
            "justify-content: center;"
            "gap: 10px;"
            "width: 100%;"
            "padding: 12px 16px;"
            "border: 0;"
            "border-radius: 12px;"
            "font-size: 1rem;"
            "font-weight: 600;"
            "color: #fff;"
            "background: linear-gradient(135deg, var(--accent), var(--accent2));"
            "cursor: pointer;"
            "box-shadow: 0 4px 14px var(--ring);"
            "transition: filter .12s, transform .12s;"
        "}"
        "button:hover {"
            "filter: brightness(1.08);"
        "}"
        "button:active {"
            "transform: scale(.98);"
        "}"
        ".bred {"
            "background: linear-gradient(135deg, var(--danger), var(--danger2));"
            "box-shadow: 0 4px 14px var(--danger-soft);"
        "}"
        ".bgrn {"
            "background: linear-gradient(135deg, var(--ok), var(--ok2));"
            "box-shadow: 0 4px 14px var(--ok-soft);"
        "}"
        ".back {"
            "background: var(--card);"
            "color: var(--muted);"
            "border: 1px solid var(--border);"
            "box-shadow: none;"
            "font-weight: 500;"
        "}"
        /* menu tiles */
        ".mbtn {"
            "justify-content: flex-start;"
            "text-align: left;"
            "padding: 12px 14px;"
            "margin: 10px 0;"
            "background: var(--card);"
            "color: var(--text);"
            "border: 1px solid var(--border);"
            "box-shadow: var(--shadow);"
        "}"
        ".mbtn:hover {"
            "filter: none;"
            "border-color: var(--accent);"
        "}"
        ".mbtn:after {"
            "content: '\\203A';"
            "margin-left: auto;"
            "font-size: 1.3rem;"
            "color: var(--muted);"
        "}"
        ".ic {"
            "display: inline-flex;"
            "align-items: center;"
            "justify-content: center;"
            "width: 38px;"
            "height: 38px;"
            "border-radius: 11px;"
            "background: var(--accent-soft);"
            "color: var(--accent);"
            "flex: none;"
        "}"
        ".mbtn.danger .ic {"
            "background: var(--danger-soft);"
            "color: var(--danger);"
        "}"
        /* device tabs (multi-unit panel) */
        ".devtabs {"
            "display: flex;"
            "gap: 8px;"
            "overflow-x: auto;"
            "justify-content: flex-start;"
            "justify-content: safe center;"
            "margin: 0 0 12px;"
            "padding-bottom: 2px;"
            "scrollbar-width: none;"
        "}"
        ".devtabs::-webkit-scrollbar, .chips::-webkit-scrollbar {"
            "display: none;"
        "}"
        ".dtab {"
            "flex: none;"
            "width: auto;"
            "padding: 8px 14px;"
            "border-radius: 999px;"
            "background: var(--card);"
            "color: var(--text);"
            "border: 1px solid var(--border);"
            "font-size: .88rem;"
            "font-weight: 600;"
            "box-shadow: none;"
        "}"
        ".dtab:hover {"
            "filter: none;"
            "border-color: var(--accent);"
        "}"
        ".dtab.active {"
            "background: linear-gradient(135deg, var(--accent), var(--accent2));"
            "color: #fff;"
            "border-color: transparent;"
        "}"
        ".dtab.gear {"
            "color: var(--muted);"
            "padding: 8px 11px;"
        "}"
        ".devstate {"
            "display: none;"
            "text-align: center;"
            "margin: 0 0 12px;"
            "padding: 8px 12px;"
            "border-radius: 10px;"
            "font-size: .85rem;"
            "font-weight: 600;"
            "color: var(--danger);"
            "background: var(--danger-soft);"
        "}"
        /* device editor */
        ".devrow {"
            "display: flex;"
            "align-items: center;"
            "gap: 8px;"
            "padding: 8px 0;"
            "border-bottom: 1px solid var(--border);"
        "}"
        ".devrow span {"
            "flex: 1;"
            "font-size: .92rem;"
            "font-weight: 600;"
        "}"
        ".devdel {"
            "width: 34px;"
            "height: 34px;"
            "padding: 0;"
            "flex: none;"
            "border-radius: 9px;"
            "background: var(--danger-soft);"
            "color: var(--danger);"
            "box-shadow: none;"
            "font-size: .9rem;"
        "}"
        ".devadd {"
            "display: flex;"
            "gap: 8px;"
            "margin-top: 12px;"
        "}"
        ".devadd input {"
            "flex: 1;"
            "min-width: 0;"
        "}"
        ".devadd button {"
            "width: 46px;"
            "flex: none;"
            "font-size: 1.2rem;"
            "padding: 0;"
        "}"
        ".dhint {"
            "font-size: .82rem;"
            "color: var(--muted);"
            "line-height: 1.45;"
        "}"
        ".devstate.good {"
            "color: var(--ok);"
            "background: var(--ok-soft);"
        "}"
        ".devstate.info {"
            "color: var(--accent);"
            "background: var(--accent-soft);"
        "}"
        ".alloff {"
            "margin: 0 0 14px;"
        "}"
        "#histcard svg {"
            "width: 100%;"
            "height: 96px;"
            "display: block;"
        "}"
        ".histmeta {"
            "text-align: center;"
            "font-size: .78rem;"
            "color: var(--muted);"
            "margin-top: 6px;"
        "}"
        ".histrange {"
            "display: flex;"
            "justify-content: center;"
            "gap: 8px;"
            "margin-top: 8px;"
        "}"
        ".histrange button {"
            "width: auto;"
            "padding: 5px 14px;"
            "font-size: .78rem;"
            "border-radius: 999px;"
            "background: var(--card2);"
            "color: var(--muted);"
            "border: 1px solid var(--border);"
            "box-shadow: none;"
        "}"
        ".histrange button.active {"
            "background: linear-gradient(135deg, var(--accent), var(--accent2));"
            "color: #fff;"
            "border-color: transparent;"
        "}"
        /* toast notifications */
        ".toast {"
            "position: fixed;"
            "left: 50%;"
            "bottom: 26px;"
            "transform: translateX(-50%);"
            "background: var(--text);"
            "color: var(--bg);"
            "padding: 10px 20px;"
            "border-radius: 999px;"
            "font-size: .88rem;"
            "font-weight: 600;"
            "box-shadow: var(--shadow);"
            "opacity: 0;"
            "transition: opacity .25s;"
            "z-index: 60;"
            "pointer-events: none;"
            "white-space: nowrap;"
        "}"
        ".toast.show {"
            "opacity: 1;"
        "}"
        /* offline dot on device tabs */
        ".dtab {"
            "position: relative;"
        "}"
        ".dtab.off:after {"
            "content: '';"
            "position: absolute;"
            "top: 5px;"
            "right: 7px;"
            "width: 8px;"
            "height: 8px;"
            "border-radius: 50%;"
            "background: var(--danger);"
        "}"
        /* collapsible cards */
        ".fold > legend {"
            "cursor: pointer;"
            "-webkit-user-select: none;"
            "user-select: none;"
        "}"
        ".fold > legend:after {"
            "content: ' \\25BE';"
        "}"
        ".fold.open > legend:after {"
            "content: ' \\25B4';"
        "}"
        ".fold:not(.open) > :not(legend) {"
            "display: none;"
        "}"
        ".fold:not(.open) {"
            "padding-top: 0;"
            "padding-bottom: 6px;"
        "}"
        ".lsum {"
            "font-weight: 500;"
            "text-transform: none;"
            "letter-spacing: 0;"
            "opacity: .8;"
        "}"
        /* room temperature marker on the dial */
        "#droom {"
            "fill: var(--muted);"
            "stroke: var(--card);"
            "stroke-width: 2;"
            "transition: fill .25s;"
        "}"
        /* theme toggle in the footer: as quiet as the plain footer text */
        ".thbtn {"
            "display: inline-block;"
            "width: auto;"
            "padding: 4px 8px;"
            "background: transparent;"
            "color: var(--muted);"
            "border: 0;"
            "border-radius: 999px;"
            "box-shadow: none;"
            "font-size: .8rem;"
            "opacity: .7;"
            "cursor: pointer;"
        "}"
        ".navrow {"
            "display: flex;"
            "gap: 10px;"
            "margin: .8em 0;"
        "}"
        ".navrow form {"
            "flex: 1;"
            "margin: 0;"
        "}"
        /* schedule timers */
        ".wdays {"
            "display: flex;"
            "gap: 6px;"
            "margin: 4px 0 10px;"
        "}"
        ".wd {"
            "flex: 1;"
            "width: auto;"
            "height: 38px;"
            "padding: 0;"
            "border-radius: 10px;"
            "background: var(--card2);"
            "border: 1px solid var(--border);"
            "color: var(--muted);"
            "font-size: .8rem;"
            "font-weight: 600;"
            "box-shadow: none;"
        "}"
        ".wd:hover {"
            "filter: none;"
            "border-color: var(--accent);"
        "}"
        ".wd.on {"
            "background: linear-gradient(135deg, var(--accent), var(--accent2));"
            "color: #fff;"
            "border-color: transparent;"
        "}"
        ".trow2 {"
            "display: flex;"
            "gap: 10px;"
        "}"
        ".trow2 p {"
            "flex: 1;"
            "min-width: 0;"
        "}"
        ".ckrow {"
            "display: flex;"
            "align-items: center;"
            "gap: 8px;"
            "font-size: .95rem;"
            "font-weight: 600;"
        "}"
        ".ckrow input {"
            "width: 1.1em;"
            "height: 1.1em;"
        "}"
        ".tempty {"
            "text-align: center;"
            "color: var(--muted);"
            "font-size: .9rem;"
            "padding: 18px 0;"
        "}"
        ".trule {"
            "display: flex;"
            "align-items: center;"
            "gap: 12px;"
            "padding: 12px 14px;"
            "margin: 0 0 10px;"
            "background: var(--card);"
            "border: 1px solid var(--border);"
            "border-radius: 14px;"
            "box-shadow: var(--shadow);"
        "}"
        ".trule.toffed .tinfo {"
            "opacity: .45;"
        "}"
        ".trule .switch {"
            "flex: none;"
        "}"
        ".tinfo {"
            "flex: 1;"
            "min-width: 0;"
        "}"
        ".tinfo b {"
            "display: block;"
            "font-size: .92rem;"
        "}"
        ".tinfo small {"
            "color: var(--muted);"
            "font-size: .78rem;"
        "}"
        /* control page */
        ".hero {"
            "text-align: center;"
            "margin: 6px 0 16px;"
        "}"
        ".hero .hlabel {"
            "display: block;"
            "font-size: .78rem;"
            "font-weight: 600;"
            "letter-spacing: .1em;"
            "text-transform: uppercase;"
            "color: var(--muted);"
        "}"
        ".hero .htemp {"
            "font-size: 1.5rem;"
            "font-weight: 700;"
            "line-height: 1.2;"
        "}"
        ".ctrlrow {"
            "padding: 0px !important;"
            "margin: 0 !important;"
        "}"
        "fieldset > .ctrlrow {"
            "display: flex;"
            "align-items: center;"
            "justify-content: space-between;"
            "gap: 12px;"
            "padding: 13px 0 !important;"
            "border-top: 1px solid var(--border);"
        "}"
        "fieldset > .ctrlrow:first-of-type {"
            "border-top: 0;"
        "}"
        ".ctrlrow p {"
            "margin: 0;"
        "}"
        ".ctrlrow p > b, .rowhead b {"
            "display: inline;"
            "font-size: .95rem;"
            "font-weight: 600;"
            "color: var(--text);"
            "margin: 0;"
        "}"
        ".ctrlrow form {"
            "margin: 0;"
        "}"
        /* thermostat dial */
        ".dialwrap {"
            "position: relative;"
            "width: min(80vw, 300px);"
            "margin: 4px auto 0;"
            "-webkit-user-select: none;"
            "user-select: none;"
        "}"
        ".dialwrap svg {"
            "width: 100%;"
            "height: auto;"
            "display: block;"
            "touch-action: none;"
            "cursor: pointer;"
        "}"
        "#dtrack {"
            "stroke: var(--accent-soft);"
            "stroke-width: 26;"
        "}"
        "#dfill {"
            "stroke: var(--accent);"
            "stroke-width: 26;"
            "transition: stroke .25s;"
        "}"
        "#dknob {"
            "fill: var(--card);"
            "stroke: var(--accent);"
            "stroke-width: 5;"
            "transition: stroke .25s;"
        "}"
        ".m-heat #dfill, .m-heat #dknob { stroke: #f59e0b; }"
        ".m-dry #dfill, .m-dry #dknob { stroke: #14b8a6; }"
        ".m-auto #dfill, .m-auto #dknob { stroke: #10b981; }"
        ".m-fan #dfill, .m-fan #dknob { stroke: #8b5cf6; }"
        ".m-off #dfill, .m-off #dknob { stroke: var(--muted); }"
        ".dcenter {"
            "position: absolute;"
            "inset: 0;"
            "display: flex;"
            "flex-direction: column;"
            "align-items: center;"
            "justify-content: center;"
            "pointer-events: none;"
        "}"
        ".dlabel {"
            "font-size: .72rem;"
            "font-weight: 600;"
            "letter-spacing: .1em;"
            "text-transform: uppercase;"
            "color: var(--muted);"
        "}"
        ".dtemp {"
            "font-size: 3.2rem;"
            "font-weight: 700;"
            "line-height: 1.1;"
        "}"
        ".dscale {"
            "font-size: 1.2rem;"
            "font-weight: 600;"
            "color: var(--muted);"
            "vertical-align: super;"
        "}"
        ".dbtns {"
            "display: flex;"
            "justify-content: center;"
            "gap: 26px;"
            "margin: -46px 0 8px;"
            "position: relative;"
        "}"
        "button.temp {"
            "width: 52px;"
            "height: 52px;"
            "padding: 0;"
            "border-radius: 50%;"
            "font-size: 1.5rem;"
            "font-weight: 500;"
            "flex: none;"
            "color: var(--accent);"
            "background: var(--card);"
            "box-shadow: var(--shadow);"
            "border: 1px solid var(--border);"
        "}"
        "button.temp:hover {"
            "filter: none;"
            "border-color: var(--accent);"
        "}"
        /* ad-hoc + night + clean mode buttons */
        ".boostrow {"
            "display: flex;"
            "flex-wrap: wrap;"
            "gap: 10px;"
            "margin: 2px 0 12px;"
        "}"
        ".boostrow button {"
            "flex: 1 1 40%;"
            "min-width: 0;"
            "margin: 0;"
        "}"
        "button.adhoc {"
            "background: linear-gradient(135deg, #f59e0b, #f97316);"
            "box-shadow: 0 4px 14px rgba(245,158,11,.3);"
            "font-size: .92rem;"
            "padding: 12px 8px;"
        "}"
        "button.adhoc.on {"
            "background: var(--danger-soft);"
            "color: var(--danger);"
            "box-shadow: none;"
            "border: 1px solid var(--border);"
        "}"
        "button.night {"
            "background: linear-gradient(135deg, #6366f1, #8b5cf6);"
            "box-shadow: 0 4px 14px rgba(99,102,241,.3);"
            "font-size: .92rem;"
            "padding: 12px 8px;"
        "}"
        "button.night.on {"
            "background: #312e81;"
            "color: #c7d2fe;"
            "box-shadow: none;"
            "border: 1px solid #4338ca;"
        "}"
        "button.clean {"
            "background: linear-gradient(135deg, #14b8a6, #06b6d4);"
            "box-shadow: 0 4px 14px rgba(20,184,166,.3);"
            "font-size: .92rem;"
            "padding: 12px 8px;"
        "}"
        "button.clean.on {"
            "background: var(--danger-soft);"
            "color: var(--danger);"
            "box-shadow: none;"
            "border: 1px solid var(--border);"
        "}"
        /* mode/fan/vane chips */
        ".chips {"
            "display: flex;"
            "gap: 8px;"
            "overflow-x: auto;"
            "padding: 13px 0 4px;"
            "border-top: 1px solid var(--border);"
            "scrollbar-width: none;"
        "}"
        "label.chip {"
            "flex: none;"
            "display: flex;"
            "flex-direction: column;"
            "gap: 2px;"
            "padding: 8px 12px;"
            "background: var(--card2);"
            "border: 1px solid var(--border);"
            "border-radius: 12px;"
            "min-width: 105px;"
        "}"
        ".chip .clabel {"
            "font-size: .68rem;"
            "font-weight: 600;"
            "letter-spacing: .06em;"
            "text-transform: uppercase;"
            "color: var(--muted);"
        "}"
        ".chip select {"
            "border: 0;"
            "background-color: transparent;"
            "padding: 0 18px 0 0;"
            "width: auto;"
            "font-weight: 600;"
            "font-size: .92rem;"
            "background-position: right 2px center, right 7px center;"
            "background-position: calc(100% - 2px) 55%, calc(100% - 7px) 55%;"
        "}"
        ".chip select:focus {"
            "box-shadow: none;"
        "}"
        /* status page key/value rows */
        ".kv {"
            "display: flex;"
            "align-items: baseline;"
            "justify-content: space-between;"
            "gap: 12px;"
            "padding: 9px 0;"
            "border-bottom: 1px solid var(--border);"
            "font-size: .9rem;"
        "}"
        ".kv:last-child {"
            "border-bottom: 0;"
        "}"
        ".kv .k {"
            "color: var(--muted);"
            "flex: none;"
        "}"
        ".kv .v {"
            "font-weight: 600;"
            "text-align: right;"
            "word-break: break-all;"
        "}"
        /* legacy colored values injected by firmware */
        "font[color='green'] { color: var(--ok); }"
        "font[color='red'] { color: var(--danger); }"
        "font[color='blue'] { color: var(--accent); }"
        "font[color='orange'] { color: var(--warn); }"
        /* ON/OFF switch */
        ".switch {"
            "position: relative;"
            "display: inline-block;"
            "width: 54px;"
            "height: 32px;"
            "flex: none;"
        "}"
        ".switch input {"
            "opacity: 0;"
            "width: 0;"
            "height: 0;"
        "}"
        ".slider {"
            "position: absolute;"
            "cursor: pointer;"
            "top: 0;"
            "left: 0;"
            "right: 0;"
            "bottom: 0;"
            "background-color: var(--card2);"
            "border: 1px solid var(--border);"
            "transition: 0.3s;"
        "}"
        ".slider:before {"
            "position: absolute;"
            "content: '';"
            "height: 24px;"
            "width: 24px;"
            "left: 3px;"
            "bottom: 3px;"
            "background-color: #fff;"
            "box-shadow: 0 2px 6px rgba(0,0,0,.25);"
            "transition: 0.3s;"
        "}"
        "input:checked + .slider {"
            "background: linear-gradient(135deg, var(--ok), var(--ok2));"
            "border-color: transparent;"
        "}"
        "input:focus + .slider {"
            "box-shadow: 0 0 0 3px var(--ring);"
        "}"
        "input:checked + .slider:before {"
            "transform: translateX(22px);"
        "}"
        ".slider.round {"
            "border-radius: 34px;"
        "}"
        ".slider.round:before {"
            "border-radius: 50%;"
        "}"
        /* footer */
        ".foot {"
            "text-align: center;"
            "margin-top: 18px;"
        "}"
        ".foot span {"
            "display: inline-block;"
            "padding: 4px 12px;"
            "font-size: .7rem;"
            "font-weight: 600;"
            "letter-spacing: .05em;"
            "color: var(--muted);"
            "background: var(--card);"
            "border: 1px solid var(--border);"
            "border-radius: 999px;"
        "}"
        ".foot .hrt {"
            "padding: 0;"
            "border: 0;"
            "background: transparent;"
            "color: #ef4444;"
            "font-size: .8rem;"
        "}"
;

const char html_common_header[] PROGMEM =
"<!DOCTYPE html>"
"<html lang='en' class=''>"
"<head>"
    "<meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no' />"
    "<meta name='theme-color' content='#2563eb'>"
    "<meta name='apple-mobile-web-app-capable' content='yes'>"
    "<meta name='apple-mobile-web-app-status-bar-style' content='default'>"
    "<title>Klimasteuerung - _UNIT_NAME_</title>"
    "<link rel='manifest' href='/manifest.json'>"
    "<link rel='icon' type='image/png' href='/icon-192.png'>"
    "<link rel='apple-touch-icon' href='/icon-192.png'>"
    "<script>try{var _t=localStorage.getItem('ks_theme');if(_t){document.documentElement.setAttribute('data-theme',_t);}}catch(e){}</script>"
    "<link rel='stylesheet' href='/style.css?v=_KS_VERSION_'>"
"</head>"
"<body>"
  "<div class='main'>"
    "<div>"
        "<noscript>To use _APP_NAME_, you need to activate Javascript"
                "<br/>"
        "</noscript>"
        "<header class='top'>"
            "<span class='mark'>"
                "<svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                    "<path d='M3 11l9-7 9 7'/>"
                    "<path d='M5 9.5V20h14V9.5'/>"
                    "<path d='M12 11v6M9.4 12.5l5.2 3M14.6 12.5l-5.2 3'/>"
                "</svg>"
            "</span>"
            "<span class='tt'><h3>Klimasteuerung</h3><span class='app'>_UNIT_NAME_</span></span>"
            "<a href='/setup' id='ksgear' class='gearlink' title='Einstellungen'>"
                "<svg width='22' height='22' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'>"
                    "<circle cx='12' cy='12' r='3'/>"
                    "<path d='M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33 1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82 1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z'/>"
                "</svg>"
            "</a>"
        "</header>"
     "</div>";

const char html_manifest[] PROGMEM =
"{"
  "\"name\":\"Klimasteuerung\","
  "\"short_name\":\"Klima\","
  "\"start_url\":\"/\","
  "\"display\":\"standalone\","
  "\"background_color\":\"#f2f5fa\","
  "\"theme_color\":\"#2563eb\","
  "\"icons\":["
    "{\"src\":\"/icon-192.png\",\"sizes\":\"192x192\",\"type\":\"image/png\"},"
    "{\"src\":\"/icon-512.png\",\"sizes\":\"512x512\",\"type\":\"image/png\"}"
  "],"
  "\"shortcuts\":["
    "{\"name\":\"Ad-hoc starten\",\"url\":\"/?adhoc=1\",\"icons\":[{\"src\":\"/icon-192.png\",\"sizes\":\"192x192\"}]},"
    "{\"name\":\"Alle Ger\\u00e4te aus\",\"url\":\"/?alloff=1\",\"icons\":[{\"src\":\"/icon-192.png\",\"sizes\":\"192x192\"}]}"
  "]"
"}";

const char html_common_footer[] PROGMEM =
    "<script>"
        "(function() {"
            "var e = document.querySelector('.tt .app');"
            "if (e) {"
                "var t = e.innerHTML.replace(/^HVAC[-_ ]*/i, '');"
                "if (t) { e.innerHTML = t; }"
            "}"
            "var g = document.getElementById('ksgear');"
            "var p = location.pathname;"
            "if (g && (p == '/' || p.indexOf('/control') == 0)) { g.style.display = 'inline-block'; }"
        "})();"
        "var _toastT = null;"
        "window.toast = function(msg) {"
            "var e = document.getElementById('kstoast');"
            "if (!e) {"
                "e = document.createElement('div');"
                "e.id = 'kstoast';"
                "e.className = 'toast';"
                "document.body.appendChild(e);"
            "}"
            "e.textContent = msg;"
            "e.classList.add('show');"
            "clearTimeout(_toastT);"
            "_toastT = setTimeout(function() { e.classList.remove('show'); }, 2200);"
        "};"
        "function ksThemeLabel(t) {"
            "return t == 'dark' ? '\\u{1F319}' : (t == 'light' ? '\\u2600\\uFE0F' : '\\u25D1');"
        "}"
        "function ksCycleTheme() {"
            "var cur = '';"
            "try { cur = localStorage.getItem('ks_theme') || ''; } catch (e) {}"
            "var next = cur == '' ? 'dark' : (cur == 'dark' ? 'light' : '');"
            "try {"
                "if (next) { localStorage.setItem('ks_theme', next); }"
                "else { localStorage.removeItem('ks_theme'); }"
            "} catch (e) {}"
            "if (next) { document.documentElement.setAttribute('data-theme', next); }"
            "else { document.documentElement.removeAttribute('data-theme'); }"
            "var b = document.getElementById('ksthemebtn');"
            "if (b) { b.textContent = ksThemeLabel(next); }"
        "}"
        "document.addEventListener('DOMContentLoaded', function() {"
            "var b = document.getElementById('ksthemebtn');"
            "if (b) {"
                "var cur = '';"
                "try { cur = localStorage.getItem('ks_theme') || ''; } catch (e) {}"
                "b.textContent = ksThemeLabel(cur);"
                "b.onclick = ksCycleTheme;"
            "}"
        "});"
    "</script>"
    "<div class='foot'>"
       "<span>made with <span class='hrt'>&#10084;</span> in Lingen</span>"
       " <span>v_KS_VERSION_</span>"
       " <button type='button' id='ksthemebtn' class='thbtn' title='Darstellung: Auto / Hell / Dunkel'>&#9681;</button>"
    "</div>"
    "</div>"
  "</div>"
"</body>"
"</html>";
