/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2023 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

const char html_page_reboot[] PROGMEM =
        "<p>_TXT_M_REBOOT_ <span id='count'>20s</span>...</p>"
        "<script>"
            "setTimeout(function() {"
                "window.location.href = '/';"
            "}, 20000);"
        "</script>";

const char html_page_reset[] PROGMEM =
        "<p>_TXT_M_RESET_ <span id='count'>20s</span>. _TXT_M_RESET_1_ _UNIT_NAME_</p>"
;


const char html_page_save_reboot[] PROGMEM =
        "<p>_TXT_M_SAVE_ <span id='count'>20s</span>...</p>"
        "<script>"
            "setTimeout(function() {"
                "window.location.href = '/';"
            "}, 20000);"
        "</script>"
;

const char html_page_mqtt[] PROGMEM =
        "<div id='l1' name='l1'>"
            "<fieldset>"
               "<legend><b>&nbsp; _TXT_MQTT_TITLE_ &nbsp;</b></legend>"
                "<form method='post'>"
                    "<p><b>_TXT_MQTT_FN_</b> _TXT_MQTT_FN_DESC_"
                        "<br/>"
                        "<input id='fn' name='fn' placeholder=' ' value='_MQTT_FN_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_HOST_</b>"
                        "<br/>"
                        "<input id='mh' name='mh' placeholder=' ' value='_MQTT_HOST_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_PORT_</b> _TXT_MQTT_PORT_DESC_"
                        "<br/>"
                        "<input id='ml' name='ml' placeholder='1883' value='_MQTT_PORT_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_USER_</b>"
                        "<br/>"
                        "<input id='mu' name='mu' placeholder='_TXT_MQTT_PH_USER_' value='_MQTT_USER_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_PASSWORD_</b>"
                        "<br/>"
                        "<input id='mp' name='mp' type='password' placeholder='_TXT_MQTT_PH_PWD_' value='_MQTT_PASSWORD_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_TOPIC_</b>"
                        "<br/>"
                        "<input id='mt' name='mt' placeholder='_TXT_MQTT_PH_TOPIC_' value='_MQTT_TOPIC_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_MQTT_ROOT_CA_CERT_</b>"
                        "<br/>"
                        "<textarea id='mrcc' name='mrcc' rows='2' cols='50' maxlength='2560'>"
                        "_MQTT_ROOT_CA_CERT_"
                        "</textarea>"
                    "</p>"
                    "<br/>"
                    "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
                "</form>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"

        "</div>"
;

const char html_page_others[] PROGMEM =
        "<div id='l1' name='l1'>"
            "<fieldset>"
                "<legend><b>&nbsp; _TXT_OTHERS_TITLE_ &nbsp;</b></legend>"
                "<form method='post'>"
                    "<p><b>_TXT_OTHERS_HAAUTO_</b>"
                        "<select name='HAA'>"
                            "<option value='ON' _HAA_ON_>_TXT_F_ON_</option>"
                            "<option value='OFF' _HAA_OFF_>_TXT_F_OFF_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_OTHERS_HATOPIC_</b>"
                        "<br/>"
                        "<input id='haat' name='haat' placeholder=' ' value='_HAA_TOPIC_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_OTHERS_DEBUG_LOGS_</b>"
                        "<select name='DebugLogs'>"
                            "<option value='ON' _DEBUG_LOGS_ON_>_TXT_F_ON_</option>"
                            "<option value='OFF' _DEBUG_LOGS_OFF_>_TXT_F_OFF_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_OTHERS_DEBUG_PCKTS_</b>"
                        "<select name='DebugPckts'>"
                            "<option value='ON' _DEBUG_PCKTS_ON_>_TXT_F_ON_</option>"
                            "<option value='OFF' _DEBUG_PCKTS_OFF_>_TXT_F_OFF_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_OTHERS_WEB_PANEL_</b>"
                        "<select name='web_p' _WEB_PN_EN_>"
                            "<option value='ON' _WEB_ON_>_TXT_F_ON_</option>"
                            "<option value='OFF' _WEB_OFF_>_TXT_F_OFF_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_TX_PIN_</b>"
                        "<br/>"
                        "<input type='number' id='tx_pin' step='1' min='0' max='33' name='tx_pin' placeholder=' ' value='_TX_PIN_'>"
                    "</p>"
                    "<p><b>_TXT_RX_PIN_</b>"
                        "<br/>"
                        "<input type='number' id='rx_pin' step='1' min='0' max='33' name='rx_pin' placeholder=' ' value='_RX_PIN_'>"
                    "</p>"
                    "<p><b>_TXT_OTHERS_TIME_ZONE_</b> (<a href='https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv' target='_blank'>_SEE_TZ_LIST</a>)"
                        "<br/>"
                        "<input id='tz' name='tz' placeholder=' ' value='_TIME_ZONE_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_OTHER_NTP_SERVER_</b>"
                        "<br/>"
                        "<input id='ntp' name='ntp' placeholder='pool.ntp.org' value='_NTP_SERVER_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<br/>"
                    "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
                "</form>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"
        "</div>"
;

const char html_page_status[] PROGMEM =
        "<div id='l1' name='l1'>"
            "<fieldset>"
            "<legend><b>&nbsp; _TXT_STATUS_TITLE_ &nbsp;</b></legend>"
            "<div class='kv'><span class='k'>_TXT_STATUS_HVAC_</span><span class='v'>_HVAC_STATUS_</span></div>"
            "<div class='kv'><span class='k'>_TXT_RETRIES_HVAC_</span><span class='v'>_HVAC_RETRIES_</span></div>"
            "<div class='kv'><span class='k'>_TXT_STATUS_MQTT_</span><span class='v'>_MQTT_STATUS_</span></div>"
            "<div class='kv'><span class='k'>_TXT_STATUS_WIFI_IP_</span><span class='v'>_WIFI_IP_</span></div>"
            "<div class='kv'><span class='k'>WIFI BSSID</span><span class='v'>_WIFI_BSSID_</span></div>"
            "<div class='kv'><span class='k'>WIFI MAC</span><span class='v'>_WIFI_MAC_</span></div>"
            "<div class='kv'><span class='k'>_TXT_STATUS_WIFI_</span><span class='v'>_WIFI_STATUS_ dBm</span></div>"
            "<div class='kv'><span class='k'>_TXT_BUILD_VERSION_</span><span class='v'>_BUILD_VERSION_</span></div>"
            "<div class='kv'><span class='k'>_TXT_BUILD_DATE_</span><span class='v'>_BUILD_DATE_</span></div>"
            "<div class='kv'><span class='k'>_TXT_STATUS_FREEHEAP_</span><span class='v'>_FREE_HEAP_</span></div>"
            "<div class='kv'><span class='k'>_TXT_CURRENT_TIME_</span><span class='v'>_CURRENT_TIME_</span></div>"
            "<div class='kv'><span class='k'>_TXT_BOOT_TIME</span><span class='v'>_BOOT_TIME_</span></div>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"
        "</div>";

const char html_page_wifi[] PROGMEM =
        "<div id='l1' name='l1'>"
            "<fieldset>"
                "<legend><b>&nbsp; _TXT_WIFI_TITLE_ &nbsp;</b></legend>"
                "<form method='post'>"
                    "<p><b>_TXT_WIFI_HOST_</b> _TXT_WIFI_HOST_DESC_ "
                        "<br/>"
                        "<input id='hn' name='hn' placeholder=' ' value='_UNIT_NAME_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_WIFI_SSID_</b> _TXT_WIFI_SSID_ENTER_"
                    "<br/>"
                    "<input id='ssid' name='ssid' placeholder=' ' value='_SSID_' "
					"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "<br/>"
                    "<label for='network'>_TXT_WIFI_SSID_SELECT_</label>"
                    "<select id='network' name='network'>"
                        "_WIFI_OPTIONS_"
                    "</select>"
                    "</p>"
                    "<p><b>_TXT_WIFI_PSK_</b>"
                        "<br/>"
                        "<input type='password' id='psk' name='psk' placeholder=' ' value='_PSK_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_WIFI_OTAP_</b>"
                        "<br/>"
                        "<input type='password' id='otapwd' name='otapwd' placeholder=' ' value='_OTA_PWD_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>Network static IP config</b></p>"
                    "<p><b>_TXT_WIFI_STATIC_IP_</b>"
                        "<br/>"
                        "<input type='text' id='stip' name='stip' placeholder=' ' value='_WIFI_STATIC_IP_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_WIFI_STATIC_GW_</b>"
                        "<br/>"
                        "<input type='text' id='stgw' name='stgw' placeholder=' ' value='_WIFI_STATIC_GW_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_WIFI_STATIC_MASK_</b>"
                        "<br/>"
                        "<input type='text' id='stmask' name='stmask' placeholder='255.255.255.0' value='_WIFI_STATIC_MASK_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_WIFI_STATIC_DNS_</b>"
                        "<br/>"
                        "<input type='text' id='stdns' name='stdns' placeholder=' ' value='_WIFI_STATIC_DNS_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<br/>"
                    "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
                "</form>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"

        "</div>"
;

const char html_page_control[] PROGMEM =
        "<div id='devtabs' class='devtabs'></div>"
        "<div class='hero'>"
            "<span class='hlabel'>_TXT_CTRL_CTEMP_</span>"
            "<div class='htemp'><span id='room_temperature'>_ROOMTEMP_</span>&#176;</div>"
        "</div>"
        "<div id='devstate' class='devstate'></div>"
        "<div id='holbanner' class='devstate info' style='display:none'>&#127796; Urlaubsmodus aktiv &#8211; Zeitpl&#228;ne und Nacht-Automatik pausiert</div>"
        "<div id='fltbanner' class='devstate' style='display:none'></div>"
        "<div id='l1' name='l1'>"
            "<fieldset id='ctrlcard'>"
                "<legend><b>&nbsp; _TXT_CTRL_TITLE_ &nbsp;</b></legend>"
                "<div class='dialwrap'>"
                    "<svg id='dial' viewBox='0 0 300 300'>"
                        "<path id='dtrack' fill='none' stroke-linecap='round'/>"
                        "<path id='dfill' fill='none' stroke-linecap='round'/>"
                        "<circle id='droom' r='6' style='display:none'/>"
                        "<circle id='dknob' r='13'/>"
                    "</svg>"
                    "<div class='dcenter'>"
                        "<span class='dlabel'>_TXT_CTRL_TEMP_</span>"
                        "<div class='dtemp'><span id='TEMP'>_TEMP_</span><span class='dscale' id='tempScale'>&#176;_TEMP_SCALE_</span></div>"
                    "</div>"
                "</div>"
                "<div class='dbtns'>"
                    "<button type='button' id='tdown' class='temp'>&#8722;</button>"
                    "<button type='button' id='tup' class='temp'>+</button>"
                "</div>"
                "<div class='boostrow'>"
                    "<button type='button' id='ADHOCBTN' class='button adhoc'>&#9889; Ad-hoc</button>"
                    "<button type='button' id='NIGHTBTN' class='button night'>&#127769; Nachtmodus</button>"
                    "<button type='button' id='CLEANBTN' class='button clean'>&#129532; Selbstreinigung</button>"
                "</div>"
                "<div class='ctrlrow'>"
                    "<p><b>_TXT_CTRL_POWER_</b></p>"
                    "<label class='switch'>"
                        "<input id='POWER' type='checkbox' value='ON' _POWER_>"
                        "<div class='slider round'></div>"
                    "</label>"
                "</div>"
                "<div class='chips'>";

const char html_page_control_mode[] PROGMEM =
                "<label class='chip'>"
                    "<span class='clabel'>_TXT_CTRL_MODE_</span>"
                    "<select name='MODE' id='MODE'>"
                        "<option value='SMART'>&#127777;&#65039; Automatik</option>"
                        "<option value='AUTO' _MODE_A_>&#10024; _TXT_F_AUTO_</option>"
                        "<option value='DRY' _MODE_D_>&#128167; _TXT_F_DRY_</option>"
                        "<option value='COOL' _MODE_C_>&#10052;&#65039; _TXT_F_COOL_</option>"
                        "<option _HEAT_HIDDEN_ value='HEAT' _MODE_H_>&#9728;&#65039; _TXT_F_HEAT_</option>"
                        "<option value='FAN' _MODE_F_>&#10051; _TXT_F_FAN_</option>"
                    "</select>"
                "</label>";

const char html_page_control_fan[] PROGMEM =
                "<label class='chip'>"
                    "<span class='clabel'>_TXT_CTRL_FAN_</span>"
                    "<select name='FAN' id='FAN'>"
                        "<option value='AUTO' _FAN_A_>&#10024; _TXT_F_AUTO_</option>"
                        "<option _QUIET_HIDDEN_ value='QUIET' _FAN_Q_>&#9601; _TXT_F_QUIET_</option>"
                        "<option value='1' _FAN_1_>&#9602; _TXT_F_LOW_</option>"
                        "<option value='2' _FAN_2_>&#9602;&#9604; _TXT_F_MEDIUM_</option>"
                        "<option value='3' _FAN_3_>&#9602;&#9604;&#9606; _TXT_F_MIDDLE_</option>"
                        "<option value='4' _FAN_4_>&#9602;&#9604;&#9606;&#9608; _TXT_F_HIGH_</option>"
                    "</select>"
                "</label>";

const char html_page_control_vane[] PROGMEM =
                "<label class='chip' _VANE_STYLE_>"
                    "<span class='clabel'>_TXT_CTRL_VANE_</span>"
                    "<select name='VANE' id='VANE'>"
                        "<option value='AUTO' _VANE_A_>&#10024; _TXT_F_AUTO_</option>"
                        "<option value='SWING' _VANE_S_>&#9887; _TXT_F_SWING_</option>"
                        "<option value='1' _VANE_1_>&#10143; _TXT_F_POS_ 1</option>"
                        "<option value='2' _VANE_2_>&#10143; _TXT_F_POS_ 2</option>"
                        "<option value='3' _VANE_3_>&#10143; _TXT_F_POS_ 3</option>"
                        "<option value='4' _VANE_4_>&#10143; _TXT_F_POS_ 4</option>"
                        "<option value='5' _VANE_5_>&#10143; _TXT_F_POS_ 5</option>"
                    "</select>"
                "</label>";

const char html_page_control_widevane[] PROGMEM =
                "<label class='chip' _WIDE_VANE_STYLE_>"
                    "<span class='clabel'>_TXT_CTRL_WVANE_</span>"
                    "<select name='WIDEVANE' id='WIDEVANE'>"
                        "<option value='SWING' _WVANE_S_>&#9887; _TXT_F_SWING_</option>"
                        "<option value='<<' _WVANE_1_><< _TXT_F_POS_ 1</option>"
                        "<option value='<' _WVANE_2_>< _TXT_F_POS_ 2</option>"
                        "<option value='|' _WVANE_3_>| _TXT_F_POS_ 3</option>"
                        "<option value='>' _WVANE_4_>> _TXT_F_POS_ 4</option>"
                        "<option value='>>' _WVANE_5_>>> _TXT_F_POS_ 5</option>"
                        "<option value='<>' _WVANE_6_><> _TXT_F_POS_ 6</option>"
                    "</select>"
                "</label>";

const char html_page_control_footer[] PROGMEM =
                "</div>"
            "</fieldset>"
            "<button type='button' id='ALLOFFBTN' class='button back alloff' style='display:none'>&#9211; Alle Ger&#228;te ausschalten</button>"
            "<fieldset id='histcard' style='display:none'>"
                "<legend><b>&nbsp; Verlauf &nbsp;</b></legend>"
                "<svg id='histsvg' viewBox='0 0 300 96' preserveAspectRatio='none'></svg>"
                "<div class='histmeta' id='histmeta'></div>"
                "<div class='histrange'>"
                    "<button type='button' id='hr24' class='active'>24 h</button>"
                    "<button type='button' id='hr7'>7 Tage</button>"
                "</div>"
            "</fieldset>"
            "<div class='navrow'>"
			    "<form action='/timers' method='get'>"
                    "<button class='back'>&#128337; Zeitpl&#228;ne</button>"
                "</form>"
            "</div>"
        "</div>";

const char html_page_unit[] PROGMEM =
        "<div id='l1' name='l1'>"
            "<fieldset>"
                "<legend><b>&nbsp; _TXT_UNIT_TITLE_ &nbsp;</b></legend>"
                "<form method='post' onsubmit=\"return matchPassword()\">"
                    "<p>"
                       "<b>_TXT_UNIT_LANGUAGE_</b>"
                       "<br/>"
                       "<select id='language' name='language' onchange=\"sendLanguage(this)\">"
                          "_LANGUAGE_OPTIONS_"
                       "</select>"
                    "</p>"
                    "<p>"
                        "<b>_TXT_UNIT_TEMP_</b>"
                        "<select name='tu'>"
                            "<option value='cel' _TU_CEL_>_TXT_F_CELSIUS_</option>"
                            "<option value='fah' _TU_FAH_>_TXT_F_FH_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_UNIT_STEPTEMP_</b>"
                        "<br/>"
                        "<input type='number' id='temp_step' step='0.1' min='0.1' max='1.0' name='temp_step' placeholder=' ' value='_TEMP_STEP_'>"
                    "</p>"

                    "<p>"
                        "<b>_TXT_UNIT_MODES_</b>"
                        "<select name='md'>"
                            "<option value='all' _MD_ALL_>_TXT_F_ALLMODES_</option>"
                            "<option value='nht' _MD_NONHEAT_>_TXT_F_NOHEAT_</option>"
                        "</select>"
                    "</p>"
                    "<p>"
                        "<b>_TXT_UNIT_FAN_MODES_</b>"
                        "<select name='mdf'>"
                            "<option value='allf' _MDF_ALL_>_TXT_F_ALLMODES_</option>"
                            "<option value='nqm' _MDF_NONQUIET_>_TXT_F_NOQUIET_</option>"
                        "</select>"
                    "</p>"
                    "<p><b>_TXT_UNIT_PASSWORD_</b>"
                        "<br/>"
                        "<input id='lpw' name='lpw' type='password' placeholder=' ' value='_LOGIN_PASSWORD_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_UNIT_PASSWORD_CONFIRM_</b>"
                        "<br/>"
                        "<input id='lpwc' name='lpwc' type='password' placeholder=' ' value='_LOGIN_PASSWORD_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<span id='message_not_match' style='color:red'> </span> <br>"
                    "<p>_TXT_UNIT_LOGIN_USERNAME_ <b>admin</b></p>"
                    "<br/>"
                    "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
                "</form>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"

        "</div>"
;

const char html_page_login[] PROGMEM =
    "<script>"
        "var loginSucess = _LOGIN_SUCCESS_;"
        "document.onreadystatechange = function() {"
            "if (document.readyState === 'complete') {"
                "if (loginSucess == 1) {"
                    "var element = document.getElementById('login_form');"
                    "element.parentNode.removeChild(element);"
                "}"
            "}"
        "}"
    "</script>"
        "<div id='login_form' name='login_form'>"
            "<fieldset>"
                "<legend><b>&nbsp; _TXT_LOGIN_TITLE_ &nbsp;</b></legend>"
                "<form action='/login' method='post'>"
                    "<p><b>_TXT_LOGIN_USERNAME_</b>"
                        "<input type='text' name='USERNAME' placeholder='_TXT_LOGIN_PH_USER_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<p><b>_TXT_LOGIN_PASSWORD_</b>"
                        "<input type='password' name='PASSWORD' placeholder='_TXT_LOGIN_PH_PWD_' "
						"autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false'>"
                    "</p>"
                    "<br/>"
                    "<button name='SUBMIT' type='submit' class='button bgrn'>_TXT_LOGIN_</button>"
                "</form>"
                "<br><a href='/status'>_TXT_LOGIN_OPEN_STATUS_</a>"
                "<br>"
            "</fieldset>"
        "</div>"
        "<div"
        "_LOGIN_MSG_"
        "</div>"
;

const char html_page_upgrade[] PROGMEM =
    "<script>"
        "function eb(s) {"
            "return document.getElementById(s);"
        "}"
        "var updTimer = null;"
        "function updPoll() {"
            "fetch('/api/update')"
                ".then(function(r) { return r.json(); })"
                ".then(function(u) {"
                    "eb('updcur').textContent = 'v' + u.cur;"
                    "if (u.state == 1) {"
                        "eb('updmsg').textContent = 'Suche nach Updates ...';"
                        "return;"
                    "}"
                    "clearInterval(updTimer);"
                    "updTimer = null;"
                    "if (u.state == 3) {"
                        "eb('updmsg').textContent = 'Fehler: ' + u.err;"
                        "return;"
                    "}"
                    "if (u.state == 2) {"
                        "eb('updmsg').textContent = 'Update l\\u00e4uft \\u2013 das Ger\\u00e4t startet danach neu ...';"
                        "setTimeout(function() { window.location.href = '/'; }, 90000);"
                        "return;"
                    "}"
                    "if (u.latest) {"
                        "if (u.latest == u.cur) {"
                            "eb('updmsg').textContent = 'Die Firmware ist aktuell (v' + u.cur + ').';"
                        "} else {"
                            "eb('updmsg').textContent = 'Neue Version verf\\u00fcgbar: v' + u.latest;"
                            "eb('updgo').style.display = '';"
                        "}"
                    "}"
                "})"
                ".catch(function() {});"
        "}"
        "function updFallbackCheck() {"
            "fetch('/api/update?check=1', {method: 'POST'}).catch(function() {});"
            "if (!updTimer) { updTimer = setInterval(updPoll, 2000); }"
        "}"
        "var updInfo = null;"
        "var updLatest = '';"
        "function updCheck() {"
            "eb('updgo').style.display = 'none';"
            "eb('updmsg').textContent = 'Suche nach Updates ...';"
            "fetch('/api/update')"
                ".then(function(r) { return r.json(); })"
                ".then(function(u) {"
                    "updInfo = u;"
                    "eb('updcur').textContent = 'v' + u.cur;"
                    "return fetch('https://api.github.com/repos/' + u.repo + '/releases/latest');"
                "})"
                ".then(function(r) { if (!r.ok) { throw 0; } return r.json(); })"
                ".then(function(rel) {"
                    "var tag = String(rel.tag_name || '');"
                    "if (tag.charAt(0) == 'v') { tag = tag.slice(1); }"
                    "if (!tag) { throw 0; }"
                    "updLatest = tag;"
                    "if (tag == updInfo.cur) {"
                        "eb('updmsg').textContent = 'Die Firmware ist aktuell (v' + tag + ').';"
                    "} else {"
                        "eb('updmsg').textContent = 'Neue Version verf\\u00fcgbar: v' + tag;"
                        "eb('updgo').style.display = '';"
                    "}"
                "})"
                ".catch(function() { updFallbackCheck(); });"
        "}"
        "function updFallbackStart() {"
            "eb('updmsg').textContent = 'Update l\\u00e4uft \\u2013 bitte warten ...';"
            "fetch('/api/update?start=1', {method: 'POST'}).catch(function() {});"
            "if (!updTimer) { updTimer = setInterval(updPoll, 3000); }"
            "setTimeout(function() { window.location.href = '/'; }, 120000);"
        "}"
        "function updStart() {"
            "if (!confirm('Update jetzt installieren? Das Ger\\u00e4t startet danach neu.')) { return; }"
            "eb('updgo').style.display = 'none';"
            "if (!updInfo || !updInfo.file || !updLatest) { updFallbackStart(); return; }"
            "eb('updmsg').textContent = 'Lade v' + updLatest + ' herunter ...';"
            "fetch('https://raw.githubusercontent.com/' + updInfo.repo + '/v' + updLatest + '/firmware/' + updInfo.file)"
                ".then(function(r) { if (!r.ok) { throw 0; } return r.blob(); })"
                ".then(function(b) {"
                    "if (b.size < 100000) { throw 0; }"
                    "eb('updmsg').textContent = '\\u00dcbertrage aufs Ger\\u00e4t (' + Math.round(b.size / 1024) + ' KB) \\u2013 bitte warten ...';"
                    "var fd = new FormData();"
                    "fd.append('upload', b, updInfo.file);"
                    "return fetch('/upload', {method: 'POST', body: fd})"
                        ".then(function(r) { return r.text(); })"
                        ".then(function(t) {"
                            "if (t.indexOf(\"color='green'\") >= 0) {"
                                "eb('updmsg').textContent = 'Update eingespielt \\u2013 das Ger\\u00e4t startet neu ...';"
                                "setTimeout(function() { window.location.href = '/'; }, 30000);"
                            "} else {"
                                "eb('updmsg').textContent = 'Update fehlgeschlagen \\u2013 bitte den Datei-Upload unten nutzen.';"
                            "}"
                        "})"
                        ".catch(function() {"
                            "eb('updmsg').textContent = '\\u00dcbertragung unterbrochen \\u2013 wenn das Update angenommen wurde, startet das Ger\\u00e4t gleich neu.';"
                            "setTimeout(function() { window.location.href = '/'; }, 30000);"
                        "});"
                "})"
                ".catch(function() { updFallbackStart(); });"
        "}"
        "document.onreadystatechange = function() {"
            "if (document.readyState === 'complete') { updPoll(); }"
        "}"
    "</script>"
        "<div style='text-align:center;'>"
            "<h2>_TXT_FW_UPDATE_PAGE_</h2>"
        "</div>"
        "<div id='f1' style='display:block;'>"
            "<div class='ctrlrow' _FIRMWARE_UPLOAD_>"
            "<fieldset>"
                "<legend><b>&nbsp; Online-Update &nbsp;</b></legend>"
                "<div class='kv'><span class='k'>Installierte Version</span><span class='v' id='updcur'>v_KS_VERSION_</span></div>"
                "<p class='dhint' id='updmsg'>Pr&#252;ft die neueste Version auf GitHub und installiert sie direkt &#252;bers Internet.</p>"
                "<button type='button' onclick='updCheck()' class='button'>Nach Updates suchen</button>"
                "<br/>"
                "<button type='button' id='updgo' onclick='updStart()' class='button bgrn' style='display:none'>Update installieren</button>"
            "</fieldset>"
            "<fieldset>"
                "<legend><b>&nbsp; _TXT_UPGRADE_INFO_ &nbsp;</b></legend>"
                "<form method='post' action='upload' enctype='multipart/form-data'>"
                    "<br>"
                    "<input type='file' accept='.bin' name='upload'>"
                    "<br>"
                    "<br>"
                    "<button type='submit' onclick=\"eb('f1').style.display='none';eb('f2').style.display='block';this.form.submit();\" class='button bgrn'>_TXT_B_UPGRADE_</button>"
                "</form>"
            "</fieldset>"
            "</div>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"

        "</div>"
        "<div id='f2' style='display:none;text-align:center;'><b>_TXT_UPGRADE_START_ ...</b></div>"
;

const char html_page_upload[] PROGMEM =
        "<div style='text-align:center;'>"
            "<h2>_TXT_UPLOAD_FW_PAGE_</h2>"
        "</div>"
        "<div id='l1' name='l1'>"
            "<br>_UPLOAD_MSG_"
            "<p>"
			    "<form action='/upgrade' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"

        "</div>"
;

const char html_page_devices[] PROGMEM =
        "<div style='text-align:center;'>"
            "<h2>Ger&#228;te</h2>"
        "</div>"
        "<div id='l1' name='l1'>"
            "<div id='dstate' class='devstate'></div>"
            "<fieldset>"
                "<legend><b>&nbsp; Betriebsart &nbsp;</b></legend>"
                "<p class='dhint'>Einzelger&#228;t: Die Oberfl&#228;che steuert nur diese Anlage &#8211; Tab-Leiste, Ger&#228;teauswahl und Synchronisierung werden ausgeblendet. Mehrere Ger&#228;te: Alle verkn&#252;pften Einheiten lassen sich &#252;ber Tabs steuern und gemeinsam verwalten.</p>"
                "<div class='trow2'>"
                    "<p><button type='button' id='bmsingle' class='button'>Einzelger&#228;t</button></p>"
                    "<p><button type='button' id='bmmulti' class='button'>Mehrere Ger&#228;te</button></p>"
                "</div>"
            "</fieldset>"
            "<fieldset id='dlistcard'>"
                "<legend><b>&nbsp; Verkn&#252;pfte Ger&#228;te &nbsp;</b></legend>"
                "<p class='dhint'>Alle Einheiten eintragen (Name + IP/Hostname) &#8211; auch diese hier. Jedes Ger&#228;t blendet sich selbst in den Tabs aus. Mit &#8222;An alle verteilen&#8220; wird die Liste auf alle eingetragenen Ger&#228;te &#252;bertragen, damit jede Weboberfl&#228;che jede Klimaanlage steuern kann. Funktioniert auch ohne verbundene Klimaanlage &#8211; ideal zur Vorbereitung vor der Installation.</p>"
                "<div id='devlist'></div>"
                "<div class='devadd'>"
                    "<input id='devname' placeholder='Name'>"
                    "<input id='devaddr' placeholder='IP / Hostname'>"
                    "<button type='button' id='devaddbtn' class='bgrn'>+</button>"
                "</div>"
                "<br/>"
                "<button type='button' id='devsync' class='button'>An alle Ger&#228;te verteilen</button>"
            "</fieldset>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"
        "</div>"
;

const char html_page_backup[] PROGMEM =
        "<div style='text-align:center;'>"
            "<h2>Sicherung</h2>"
        "</div>"
        "<div id='l1' name='l1'>"
            "<div id='bstate' class='devstate'></div>"
            "<div id='bmain'>"
                "<fieldset>"
                    "<legend><b>&nbsp; Sicherung erstellen &nbsp;</b></legend>"
                    "<p class='dhint'>Speichert alle Einstellungen dieses Ger&#228;ts (WLAN, MQTT, Einheit, Ger&#228;teliste, Zeitpl&#228;ne, Nacht-, Filter- und Urlaubsmodus) in einer Datei. Achtung: Die Datei enth&#228;lt Passw&#246;rter im Klartext &#8211; sicher aufbewahren.</p>"
                    "<button type='button' id='bdl' class='button bgrn'>Sicherung herunterladen</button>"
                "</fieldset>"
                "<fieldset>"
                    "<legend><b>&nbsp; Wiederherstellen &nbsp;</b></legend>"
                    "<p class='dhint'>Spielt eine zuvor heruntergeladene Sicherung ein und &#252;berschreibt die aktuellen Einstellungen. Das Ger&#228;t startet danach automatisch neu.</p>"
                    "<p><input type='file' id='bfile' accept='.json,application/json'></p>"
                    "<br/>"
                    "<button type='button' id='brestore' class='button'>Sicherung wiederherstellen</button>"
                "</fieldset>"
            "</div>"
            "<div id='breboot' style='display:none;text-align:center;'>"
                "<p><b>Einstellungen wiederhergestellt &#8211; Ger&#228;t startet neu ...</b></p>"
                "<p>Weiterleitung in <span id='count'>30s</span></p>"
            "</div>"
            "<p>"
			    "<form action='/setup' method='get'>"
                    "<button class='back'>_TXT_BACK_</button>"
                "</form>"
            "</p>"
        "</div>"
;

const char html_page_timers[] PROGMEM =
        "<div style='text-align:center;'>"
            "<h2>Zeitpl&#228;ne</h2>"
        "</div>"
        "<div id='l1' name='l1'>"
            "<div id='tstate' class='devstate'></div>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Urlaubsmodus &nbsp;</b><span class='lsum' id='hsum'></span></legend>"
                "<p class='dhint'>Pausiert Zeitpl&#228;ne und Nacht-Automatik auf diesem Ger&#228;t. Optional h&#228;lt der Frostschutz die Raumtemperatur &#252;ber dem Grenzwert.</p>"
                "<p>"
                    "<label class='ckrow'><input type='checkbox' id='hon'> Urlaubsmodus aktiv</label>"
                "</p>"
                "<div class='trow2'>"
                    "<p>"
                        "<label class='ckrow'><input type='checkbox' id='hfp' checked> Frostschutz</label>"
                    "</p>"
                    "<p><b>Grenzwert (&#176;C)</b>"
                        "<input type='number' id='hft' min='5' max='25' step='0.5' value='16'>"
                    "</p>"
                "</div>"
                "<div class='trow2'>"
                    "<p><button type='button' id='hsave' class='button bgrn'>Speichern</button></p>"
                    "<p><button type='button' id='hsync' class='button'>Auf alle Ger&#228;te &#252;bertragen</button></p>"
                "</div>"
            "</fieldset>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Filter &nbsp;</b><span class='lsum' id='flsum'></span></legend>"
                "<p class='dhint'>Z&#228;hlt die Betriebsstunden der Anlage. Nach Erreichen der Grenze erscheint auf der Steuerung eine Erinnerung, den Filter zu reinigen.</p>"
                "<div class='kv'><span class='k'>Betriebsstunden seit Reinigung</span><span class='v' id='flh'>&#8211;</span></div>"
                "<div class='trow2'>"
                    "<p><b>Erinnerung nach (Stunden, 0 = aus)</b>"
                        "<input type='number' id='flth' min='0' max='1000' step='10' value='100'>"
                    "</p>"
                    "<p><b>&nbsp;</b>"
                        "<button type='button' id='flsave' class='button bgrn'>Speichern</button>"
                    "</p>"
                "</div>"
                "<button type='button' id='flreset' class='button back'>Filter gereinigt &#8211; Z&#228;hler zur&#252;cksetzen</button>"
            "</fieldset>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Selbstreinigung &nbsp;</b><span class='lsum' id='clsum'></span></legend>"
                "<p class='dhint'>Trocknet das Innenger&#228;t nach dem Betrieb, um Schimmel und Ger&#252;che zu verhindern: Nach dem Ausschalten (nach K&#252;hlen, Entfeuchten oder Auto) l&#228;uft der L&#252;fter auf kleinster Stufe weiter und schaltet danach wirklich ab. Der &#129532;-Button auf der Steuerung startet die Reinigung auch manuell. Ein Neustart des Ger&#228;ts bricht einen laufenden Reinigungslauf ab.</p>"
                "<p>"
                    "<label class='ckrow'><input type='checkbox' id='clen'> Automatisch nach dem Ausschalten</label>"
                "</p>"
                "<div class='trow2'>"
                    "<p><b>Dauer (Minuten)</b>"
                        "<input type='number' id='clm' min='5' max='60' step='5' value='15'>"
                    "</p>"
                    "<p><b>&nbsp;</b>"
                        "<button type='button' id='clsave' class='button bgrn'>Speichern</button>"
                    "</p>"
                "</div>"
            "</fieldset>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Nachtmodus &nbsp;</b><span class='lsum' id='nsum'></span></legend>"
                "<p class='dhint'>Der &#127769; Nachtmodus-Button auf der Steuerung wendet dieses Profil an; beim Beenden werden die vorherigen Einstellungen wiederhergestellt. Optional startet er automatisch im Zeitfenster (auch &#252;ber Mitternacht), wenn die Anlage l&#228;uft.</p>"
                "<p>"
                    "<label class='ckrow'><input type='checkbox' id='nen'> Automatisch im Zeitfenster aktivieren</label>"
                "</p>"
                "<div class='trow2'>"
                    "<p><b>Von</b>"
                        "<input type='time' id='nfrom' value='22:00'>"
                    "</p>"
                    "<p><b>Bis</b>"
                        "<input type='time' id='nto' value='06:30'>"
                    "</p>"
                "</div>"
                "<div class='trow2'>"
                    "<p><b>Temperatur</b>"
                        "<input type='number' id='ntp' min='10' max='31' step='0.5' value='19'>"
                    "</p>"
                    "<p><b>Modus</b>"
                        "<select id='nmd'>"
                            "<option value=''>&#8211; unver&#228;ndert &#8211;</option>"
                            "<option value='COOL'>&#10052;&#65039; K&#252;hlen</option>"
                            "<option value='HEAT'>&#9728;&#65039; Heizen</option>"
                            "<option value='DRY'>&#128167; Entfeuchten</option>"
                            "<option value='FAN'>&#10051; L&#252;ften</option>"
                            "<option value='AUTO'>&#10024; Auto</option>"
                        "</select>"
                    "</p>"
                "</div>"
                "<div class='trow2'>"
                    "<p><b>L&#252;fter</b>"
                        "<select id='nfan'>"
                            "<option value=''>&#8211; unver&#228;ndert &#8211;</option>"
                            "<option value='QUIET'>Leise</option>"
                            "<option value='AUTO'>Auto</option>"
                            "<option value='1'>Niedrig</option>"
                            "<option value='2'>Mittel</option>"
                            "<option value='3'>Erh&#246;ht</option>"
                            "<option value='4'>Hoch</option>"
                        "</select>"
                    "</p>"
                    "<p><b>Lamelle</b>"
                        "<select id='nvane'>"
                            "<option value=''>&#8211; unver&#228;ndert &#8211;</option>"
                            "<option value='AUTO'>Auto</option>"
                            "<option value='SWING'>Schwenken</option>"
                            "<option value='1'>Position 1</option>"
                            "<option value='2'>Position 2</option>"
                            "<option value='3'>Position 3</option>"
                            "<option value='4'>Position 4</option>"
                            "<option value='5'>Position 5</option>"
                        "</select>"
                    "</p>"
                "</div>"
                "<div class='trow2'>"
                    "<p><b>Lamelle (breit)</b>"
                        "<select id='nwv'>"
                            "<option value=''>&#8211; unver&#228;ndert &#8211;</option>"
                            "<option value='SWING'>Schwenken</option>"
                            "<option value='<<'>&#171;</option>"
                            "<option value='<'>&#8249;</option>"
                            "<option value='|'>Mitte</option>"
                            "<option value='>'>&#8250;</option>"
                            "<option value='>>'>&#187;</option>"
                        "</select>"
                    "</p>"
                    "<p><b>&nbsp;</b>"
                        "<button type='button' id='nsave' class='button bgrn'>Speichern</button>"
                    "</p>"
                "</div>"
            "</fieldset>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Ad-hoc &nbsp;</b><span class='lsum' id='adsum'></span></legend>"
                "<p class='dhint'>Der &#9889; Ad-hoc-Button auf der Steuerung startet die Anlage im gew&#228;hlten Modus und schaltet sie nach dieser Laufzeit automatisch wieder aus.</p>"
                "<div class='trow2'>"
                    "<p><b>Laufzeit (Minuten)</b>"
                        "<input type='number' id='adm' min='5' max='720' step='5' value='60'>"
                    "</p>"
                    "<p><b>&nbsp;</b>"
                        "<button type='button' id='admsave' class='button bgrn'>Speichern</button>"
                    "</p>"
                "</div>"
            "</fieldset>"
            "<div id='tlist'></div>"
            "<fieldset class='fold'>"
                "<legend><b>&nbsp; Neuer Zeitplan &nbsp;</b></legend>"
                "<p><b>Ger&#228;t</b>"
                    "<select id='tdev'></select>"
                "</p>"
                "<p><b>Wiederholung</b>"
                    "<select id='trt'>"
                        "<option value='0'>Wochentage</option>"
                        "<option value='1'>Alle N Tage</option>"
                    "</select>"
                "</p>"
                "<div id='twdays' class='wdays'></div>"
                "<div id='tint' style='display:none'>"
                    "<div class='trow2'>"
                        "<p><b>Alle ... Tage</b>"
                            "<input type='number' id='tiv' min='1' max='30' step='1' value='2'>"
                        "</p>"
                        "<p><b>Ab Datum</b>"
                            "<input type='date' id='tan'>"
                        "</p>"
                    "</div>"
                "</div>"
                "<div class='trow2'>"
                    "<p><b>Von</b>"
                        "<input type='time' id='tfrom' value='08:00'>"
                    "</p>"
                    "<p><b>Bis</b>"
                        "<input type='time' id='tto' value='10:00'>"
                    "</p>"
                "</div>"
                "<div class='trow2'>"
                    "<p><b>Modus</b>"
                        "<select id='tmd'>"
                            "<option value='COOL'>&#10052;&#65039; K&#252;hlen</option>"
                            "<option value='HEAT'>&#9728;&#65039; Heizen</option>"
                            "<option value='DRY'>&#128167; Entfeuchten</option>"
                            "<option value='FAN'>&#10051; L&#252;ften</option>"
                            "<option value='AUTO'>&#10024; Auto</option>"
                        "</select>"
                    "</p>"
                    "<p><b>Temperatur</b>"
                        "<input type='number' id='ttp' min='10' max='31' step='0.5' value='21'>"
                    "</p>"
                "</div>"
                "<p>"
                    "<label class='ckrow'><input type='checkbox' id='toff' checked> Nach Ablauf ausschalten</label>"
                "</p>"
                "<br/>"
                "<button type='button' id='taddbtn' class='button bgrn'>Zeitplan hinzuf&#252;gen</button>"
            "</fieldset>"
            "<fieldset id='tcopycard' class='fold' style='display:none'>"
                "<legend><b>&nbsp; Zeitpl&#228;ne &#252;bertragen &nbsp;</b></legend>"
                "<p class='dhint'>Kopiert die obigen Zeitpl&#228;ne auf ein anderes Ger&#228;t und ersetzt dessen Liste. Die Regeln gelten dort f&#252;r das Ger&#228;t selbst.</p>"
                "<div class='trow2'>"
                    "<p><b>Zielger&#228;t</b>"
                        "<select id='tdest'></select>"
                    "</p>"
                    "<p><b>&nbsp;</b>"
                        "<button type='button' id='tcopybtn' class='button'>&#220;bertragen</button>"
                    "</p>"
                "</div>"
            "</fieldset>"
            "<p>"
			    "<form action='/' method='get'>"
                    "<button class='back'>Zur Steuerung</button>"
                "</form>"
            "</p>"
        "</div>"
;
