/*
  mitsubishi2mqtt - Mitsubishi Heat Pump to MQTT control for Home Assistant.
  Copyright (c) 2023 gysmo38, dzungpv, shampeon, endeavour, jascdk, chrdavis, alekslyse.  All right reserved.
  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.
  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

const char count_down_script[] PROGMEM = 
"<script>"
    "var count = 30;"
    "(function countDown() {"
        "document.getElementById('count').innerHTML = count + 's';"
        "setTimeout(function() {"
            "if(count > 0) {"
                "count --;"
                "return countDown();"
            "} else {"
                "window.location.href = '/';"
            "}"
        "}, 1000);"
    "})();"
"</script>"
;
const char count_down_script_init[] PROGMEM = 
"<script>"
    "var count = 30;"
    "(function countDown() {"
        "document.getElementById('count').innerHTML = count + 's';"
        "setTimeout(function() {"
            "if(count > 0) {"
                "count --;"
                "return countDown();"
            "} else {"
                "window.location.href = 'http://_HOST_NAME_/status';"
            "}"
        "}, 1000);"
    "})();"
"</script>"
;


const char fw_check_script_events[] PROGMEM = 
"<script>"
"if (!!window.EventSource) {"
 "var source = new EventSource('/events');"
 "source.addEventListener('open', function(e) {"
  "console.log('Events Connected');"
 "}, false);"
 "source.addEventListener('error', function(e) {"
  "if (e.target.readyState != EventSource.OPEN) {"
    "console.log('Events Disconnected');"
  "}"
 "}, false);"
 "source.addEventListener('message', function(e) {"
  "console.log('message', e.data);"
 "}, false);"
 "source.addEventListener('fw_check_status', function(e) {"
  "console.log('fw_check_status', e.data);"
  "document.getElementById('status').innerHTML = e.data;"
 "}, false);"
 "source.addEventListener('wifiOptions', function(e) {"
  "console.log('wifiOptions', e.data);"
  "document.getElementById('network').innerHTML = e.data;"
 "}, false);"
 "source.addEventListener('fw_check_reboot', function(e) {"
  "console.log('fw_check_status', e.data);"
  "document.getElementById('status').innerHTML = e.data;"
  "var count = 20;"
  "(function countDown() {"
        "document.getElementById('count').innerHTML = count + 's';"
        "setTimeout(function() {"
            "if(count > 0) {"
                "count --;"
                "return countDown();"
            "} else {"
                "window.location.href = '/status';"
            "}"
        "}, 1000);"
    "})();"
 "}, false);"
"}"
"</script>";

const char unit_script_ws[] PROGMEM = 
"<script>"
    "var websocket;"
    "function initWebSocket() {"
      "console.log('Trying to open a WebSocket connection...');"
      "var gateway = 'ws://${window.location.hostname}/ws';"
      "websocket = new WebSocket(\"ws://\" + location.host + \"/ws\");"
      "websocket.onopen    = onOpen;"
      "websocket.onclose   = onClose;"
      "websocket.onmessage = onMessage;"
    "}"

    "function onOpen(event) {"
      "console.log('Connection opened');"
    "}"

    "function onClose(event) {"
      "console.log('Connection closed');"
      "setTimeout(initWebSocket, 4000);"
    "}"

    "function onMessage(event) {"
      "console.log('onMessage: ' + event.data);"
      "if (event.data == 'REFRESH'){"
        "location.reload();"
      "}"
    "}"
    "window.addEventListener('load', onLoad);"

    "function onLoad(event) {"
      "initWebSocket();"
    "}"

    "function sendLanguage(obj){"
      "var lang_index = document.getElementById('language').value;"
      "console.log('send language: ' + lang_index);"
      "websocket.send('language;'+lang_index);"
    "}"
    
    "function matchPassword() {"  
      "var pw1 = document.getElementById('lpw').value;"  
      "var pw2 = document.getElementById('lpwc').value;"  
      "if(pw1 != pw2)"  
      "{"   
        "document.getElementById('message_not_match').innerHTML = '_TXT_UNIT_PASSWORD_NOT_MATCH_';"
        "return false;" 
      "}"
      "document.getElementById('message_not_match').innerHTML = '';"
      "return true;"
    "}"  
"</script>";

const char control_script_events[] PROGMEM =
    "<script>"
        "var MIN = _MIN_TEMP_;"
        "var MAX = _MAX_TEMP_;"
        "var STEP = _TEMP_STEP_;"
        "var HEATSUP = _HEAT_MODE_SUPPORT_;"
        "var QUIETSUP = _QUIET_MODE_SUPPORT_;"
        "var A0 = 135, SWEEP = 270, R = 120, CX = 150, CY = 150;"
        "var st = {min: MIN, max: MAX, step: STEP};"
        "var target = MIN;"
        "var devices = [];"
        "var cur = -1;"
        "var dragging = false;"
        "var pollTimer = null;"
        "var sendTimer = null;"
        "function $(i) { return document.getElementById(i); }"
        "function pol(a) {"
            "var r = a * Math.PI / 180;"
            "return [CX + R * Math.cos(r), CY + R * Math.sin(r)];"
        "}"
        "function arc(a1, a2) {"
            "var p1 = pol(a1), p2 = pol(a2);"
            "var lg = (a2 - a1) > 180 ? 1 : 0;"
            "return 'M ' + p1[0] + ' ' + p1[1] + ' A ' + R + ' ' + R + ' 0 ' + lg + ' 1 ' + p2[0] + ' ' + p2[1];"
        "}"
        "function fmt(v) {"
            "v = Number(v);"
            "return (Number(st.step) < 1) ? v.toFixed(1) : String(Math.round(v));"
        "}"
        "function drawDial() {"
            "$('dtrack').setAttribute('d', arc(A0, A0 + SWEEP));"
            "var f = (target - st.min) / (st.max - st.min);"
            "f = Math.max(0, Math.min(1, f));"
            "var a = A0 + f * SWEEP;"
            "$('dfill').setAttribute('d', arc(A0, Math.max(A0 + 0.5, a)));"
            "var k = pol(a);"
            "$('dknob').setAttribute('cx', k[0]);"
            "$('dknob').setAttribute('cy', k[1]);"
            "$('TEMP').innerHTML = fmt(target);"
        "}"
        "function setTarget(v, fromUser) {"
            "var s = Number(st.step) || 1;"
            "v = Math.round(v / s) * s;"
            "v = Math.max(Number(st.min), Math.min(Number(st.max), v));"
            "target = v;"
            "drawDial();"
            "if (fromUser) {"
                "clearTimeout(sendTimer);"
                "sendTimer = setTimeout(function() { send({TEMP: fmt(target)}); }, 400);"
            "}"
        "}"
        "function apiBase() { return cur < 0 ? '' : 'http://' + devices[cur].a; }"
        "function send(params) {"
            "var body = new URLSearchParams();"
            "for (var k in params) { body.append(k, params[k]); }"
            "fetch(apiBase() + '/api/control', {method: 'POST', body: body})"
                ".catch(function() { setState('offline'); });"
        "}"
        "function setMode(m) {"
            "var cls = 'm-' + String(m || '').toLowerCase();"
            "if (!$('POWER').checked) { cls = 'm-off'; }"
            "$('ctrlcard').className = cls;"
        "}"
        "function selSet(id, v) {"
            "var e = $(id);"
            "if (e && v !== undefined && v !== null) { e.value = v; }"
        "}"
        "function apply(s) {"
            "st.min = s.min; st.max = s.max; st.step = s.step;"
            "$('room_temperature').innerHTML = fmt(s.room);"
            "$('tempScale').innerHTML = '&#176;' + s.scale;"
            "$('POWER').checked = (s.power == 'ON');"
            "selSet('MODE', s.mode);"
            "selSet('FAN', s.fan);"
            "selSet('VANE', s.vane);"
            "selSet('WIDEVANE', s.widevane);"
            "if (!dragging) { target = Number(s.temp); drawDial(); }"
            "setMode(s.mode);"
            "setState(s.connected ? '' : 'hvacoff');"
        "}"
        "function setState(s) {"
            "var msgs = {offline: 'Ger\\u00e4t nicht erreichbar', auth: 'Login auf dem Ger\\u00e4t erforderlich', hvacoff: 'HVAC nicht verbunden'};"
            "var e = $('devstate');"
            "e.innerHTML = msgs[s] || '';"
            "e.style.display = msgs[s] ? '' : 'none';"
            "$('ctrlcard').style.opacity = (s == 'offline' || s == 'auth') ? '.45' : '';"
            "$('ctrlcard').style.pointerEvents = (s == 'offline' || s == 'auth') ? 'none' : '';"
        "}"
        "function refresh() {"
            "fetch(apiBase() + '/api/status')"
                ".then(function(r) {"
                    "if (r.status == 401) { setState('auth'); throw 0; }"
                    "if (!r.ok) { throw 1; }"
                    "return r.json();"
                "})"
                ".then(function(s) { apply(s); })"
                ".catch(function(e) {"
                    "if (e === 1 || e instanceof TypeError) {"
                        "if (cur >= 0) { setState('offline'); }"
                    "}"
                "});"
        "}"
        "function selectDev(idx) {"
            "cur = idx;"
            "setState('');"
            "renderTabs();"
            "if (pollTimer) { clearInterval(pollTimer); }"
            "refresh();"
            "pollTimer = setInterval(refresh, 5000);"
        "}"
        "function localName() {"
            "var h = document.querySelector('.tt .app');"
            "return h ? h.innerHTML : 'Hier';"
        "}"
        "function renderTabs() {"
            "var t = $('devtabs');"
            "t.innerHTML = '';"
            "var mk = function(label, idx) {"
                "var b = document.createElement('button');"
                "b.type = 'button';"
                "b.className = 'dtab' + (cur == idx ? ' active' : '');"
                "b.textContent = label;"
                "b.onclick = function() { selectDev(idx); };"
                "t.appendChild(b);"
            "};"
            "mk(localName(), -1);"
            "for (var i = 0; i < devices.length; i++) { mk(devices[i].n, i); }"
            "var g = document.createElement('button');"
            "g.type = 'button';"
            "g.className = 'dtab gear';"
            "g.innerHTML = '&#9881;';"
            "g.onclick = function() {"
                "var e = $('devedit');"
                "e.style.display = (e.style.display == 'none') ? '' : 'none';"
                "renderDevList();"
            "};"
            "t.appendChild(g);"
        "}"
        "function renderDevList() {"
            "var l = $('devlist');"
            "l.innerHTML = '';"
            "for (var i = 0; i < devices.length; i++) {"
                "(function(i) {"
                    "var row = document.createElement('div');"
                    "row.className = 'devrow';"
                    "var s = document.createElement('span');"
                    "s.textContent = devices[i].n + ' (' + devices[i].a + ')';"
                    "var b = document.createElement('button');"
                    "b.type = 'button';"
                    "b.className = 'devdel';"
                    "b.innerHTML = '&#10005;';"
                    "b.onclick = function() { devices.splice(i, 1); saveDevs(); };"
                    "row.appendChild(s);"
                    "row.appendChild(b);"
                    "l.appendChild(row);"
                "})(i);"
            "}"
        "}"
        "function saveDevs() {"
            "var body = new URLSearchParams();"
            "body.append('devices', JSON.stringify(devices));"
            "fetch('/api/devices', {method: 'POST', body: body})"
                ".then(function() {"
                    "if (cur >= devices.length) { cur = -1; }"
                    "renderTabs();"
                    "renderDevList();"
                "})"
                ".catch(function() {});"
        "}"
        "function loadDevs() {"
            "fetch('/api/devices')"
                ".then(function(r) { return r.ok ? r.json() : []; })"
                ".then(function(d) {"
                    "devices = (d && d.length !== undefined) ? d : [];"
                    "renderTabs();"
                "})"
                ".catch(function() { devices = []; renderTabs(); });"
        "}"
        "function evAngle(e) {"
            "var r = $('dial').getBoundingClientRect();"
            "var x = (e.clientX - r.left) / r.width * 300 - CX;"
            "var y = (e.clientY - r.top) / r.height * 300 - CY;"
            "var a = Math.atan2(y, x) * 180 / Math.PI;"
            "if (a < 0) { a += 360; }"
            "if (a > 45 && a < 135) { a = (a < 90) ? 405 : 135; }"
            "else if (a <= 45) { a += 360; }"
            "return Math.max(A0, Math.min(A0 + SWEEP, a));"
        "}"
        "function dialTo(e) {"
            "var f = (evAngle(e) - A0) / SWEEP;"
            "setTarget(Number(st.min) + f * (Number(st.max) - Number(st.min)), false);"
        "}"
        "document.onreadystatechange = function() {"
            "if (document.readyState !== 'complete') { return; }"
            "target = parseFloat($('TEMP').innerHTML) || MIN;"
            "drawDial();"
            "setMode($('MODE') ? $('MODE').value : '');"
            "var dial = $('dial');"
            "dial.addEventListener('pointerdown', function(e) {"
                "dragging = true;"
                "dial.setPointerCapture(e.pointerId);"
                "dialTo(e);"
            "});"
            "dial.addEventListener('pointermove', function(e) {"
                "if (dragging) { dialTo(e); }"
            "});"
            "dial.addEventListener('pointerup', function(e) {"
                "if (!dragging) { return; }"
                "dragging = false;"
                "setTarget(target, true);"
            "});"
            "$('tdown').onclick = function() { setTarget(target - Number(st.step), true); };"
            "$('tup').onclick = function() { setTarget(target + Number(st.step), true); };"
            "$('POWER').onchange = function() {"
                "var p = {PWRCHK: ''};"
                "if ($('POWER').checked) { p.POWER = 'ON'; }"
                "send(p);"
                "setMode($('MODE') ? $('MODE').value : '');"
            "};"
            "var sels = ['MODE', 'FAN', 'VANE', 'WIDEVANE'];"
            "for (var i = 0; i < sels.length; i++) {"
                "(function(id) {"
                    "var e = $(id);"
                    "if (!e) { return; }"
                    "e.onchange = function() {"
                        "var p = {};"
                        "p[id] = e.value;"
                        "send(p);"
                        "if (id == 'MODE') { setMode(e.value); }"
                    "};"
                "})(sels[i]);"
            "}"
            "$('devaddbtn').onclick = function() {"
                "var n = $('devname').value.trim();"
                "var a = $('devaddr').value.trim();"
                "if (!n || !a) { return; }"
                "devices.push({n: n, a: a});"
                "$('devname').value = '';"
                "$('devaddr').value = '';"
                "saveDevs();"
            "};"
            "loadDevs();"
            "refresh();"
            "pollTimer = setInterval(refresh, 5000);"
            "/*web event*/"
            "if (!!window.EventSource) {"
                "var source = new EventSource('/events');"
                "source.addEventListener('temperature', function(e) {"
                    "if (cur < 0 && !dragging) { target = parseFloat(e.data); drawDial(); }"
                "}, false);"
                "source.addEventListener('room_temperature', function(e) {"
                    "if (cur < 0) { $('room_temperature').innerHTML = e.data; }"
                "}, false);"
                "source.addEventListener('power', function(e) {"
                    "if (cur < 0) {"
                        "$('POWER').checked = (e.data == 'ON');"
                        "setMode($('MODE') ? $('MODE').value : '');"
                    "}"
                "}, false);"
                "source.addEventListener('mode', function(e) {"
                    "if (cur < 0) { selSet('MODE', e.data); setMode(e.data); }"
                "}, false);"
                "source.addEventListener('fan', function(e) {"
                    "if (cur < 0) { selSet('FAN', e.data); }"
                "}, false);"
                "source.addEventListener('vane', function(e) {"
                    "if (cur < 0) { selSet('VANE', e.data); }"
                "}, false);"
                "source.addEventListener('wideVane', function(e) {"
                    "if (cur < 0) { selSet('WIDEVANE', e.data); }"
                "}, false);"
            "}"
        "}"
    "</script>";

const char timers_script[] PROGMEM =
    "<script>"
        "var devices = [];"
        "var scheds = [];"
        "var WD = ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'];"
        "var MODES = {COOL: 'K\\u00fchlen', HEAT: 'Heizen', DRY: 'Entfeuchten', FAN: 'L\\u00fcften', AUTO: 'Auto'};"
        "function $(i) { return document.getElementById(i); }"
        "function localName() {"
            "var h = document.querySelector('.tt .app');"
            "return h ? h.innerHTML : 'Dieses Ger\\u00e4t';"
        "}"
        "function devLabel(a) {"
            "if (!a) { return localName(); }"
            "for (var i = 0; i < devices.length; i++) {"
                "if (devices[i].a == a) { return devices[i].n; }"
            "}"
            "return a;"
        "}"
        "function daysText(r) {"
            "if (r.rt == 1) { return 'Alle ' + r.iv + ' Tage (ab ' + r.an + ')'; }"
            "if (r.dm == 127) { return 'T\\u00e4glich'; }"
            "var p = [];"
            "for (var i = 0; i < 7; i++) {"
                "if (r.dm & (1 << i)) { p.push(WD[i]); }"
            "}"
            "return p.length ? p.join(' ') : '-';"
        "}"
        "function showState(msg) {"
            "var e = $('tstate');"
            "e.innerHTML = msg || '';"
            "e.style.display = msg ? '' : 'none';"
        "}"
        "function saveScheds() {"
            "var body = new URLSearchParams();"
            "body.append('schedules', JSON.stringify(scheds));"
            "fetch('/api/schedules', {method: 'POST', body: body})"
                ".then(function(r) {"
                    "if (r.ok) { showState(''); }"
                "})"
                ".catch(function() { showState('Speichern fehlgeschlagen'); });"
            "renderList();"
        "}"
        "function renderList() {"
            "var l = $('tlist');"
            "l.innerHTML = '';"
            "if (!scheds.length) {"
                "var e = document.createElement('div');"
                "e.className = 'tempty';"
                "e.textContent = 'Noch keine Zeitpl\\u00e4ne';"
                "l.appendChild(e);"
                "return;"
            "}"
            "for (var i = 0; i < scheds.length; i++) {"
                "(function(i) {"
                    "var r = scheds[i];"
                    "var row = document.createElement('div');"
                    "row.className = 'trule' + (r.en ? '' : ' toffed');"
                    "var sw = document.createElement('label');"
                    "sw.className = 'switch tsw';"
                    "var cb = document.createElement('input');"
                    "cb.type = 'checkbox';"
                    "cb.checked = !!r.en;"
                    "cb.onchange = function() { r.en = cb.checked ? 1 : 0; saveScheds(); };"
                    "var sl = document.createElement('div');"
                    "sl.className = 'slider round';"
                    "sw.appendChild(cb);"
                    "sw.appendChild(sl);"
                    "var info = document.createElement('div');"
                    "info.className = 'tinfo';"
                    "var b = document.createElement('b');"
                    "b.textContent = devLabel(r.a) + ' \\u00b7 ' + (MODES[r.md] || r.md) + ' ' + r.tp + '\\u00b0';"
                    "var s = document.createElement('small');"
                    "s.textContent = daysText(r) + ' \\u00b7 ' + r.f + '\\u2013' + r.t + (r.off ? ' \\u00b7 danach aus' : '');"
                    "info.appendChild(b);"
                    "info.appendChild(s);"
                    "var del = document.createElement('button');"
                    "del.type = 'button';"
                    "del.className = 'devdel';"
                    "del.innerHTML = '&#10005;';"
                    "del.onclick = function() { scheds.splice(i, 1); saveScheds(); };"
                    "row.appendChild(sw);"
                    "row.appendChild(info);"
                    "row.appendChild(del);"
                    "l.appendChild(row);"
                "})(i);"
            "}"
        "}"
        "function fillDevs() {"
            "var s = $('tdev');"
            "s.innerHTML = '';"
            "var o = document.createElement('option');"
            "o.value = '';"
            "o.textContent = localName();"
            "s.appendChild(o);"
            "for (var i = 0; i < devices.length; i++) {"
                "var d = document.createElement('option');"
                "d.value = devices[i].a;"
                "d.textContent = devices[i].n;"
                "s.appendChild(d);"
            "}"
        "}"
        "function buildWdays() {"
            "var w = $('twdays');"
            "for (var i = 0; i < 7; i++) {"
                "(function(i) {"
                    "var b = document.createElement('button');"
                    "b.type = 'button';"
                    "b.className = 'wd on';"
                    "b.textContent = WD[i];"
                    "b.onclick = function() { b.classList.toggle('on'); };"
                    "w.appendChild(b);"
                "})(i);"
            "}"
        "}"
        "function todayStr() {"
            "var d = new Date();"
            "var m = d.getMonth() + 1;"
            "var t = d.getDate();"
            "return d.getFullYear() + '-' + (m < 10 ? '0' : '') + m + '-' + (t < 10 ? '0' : '') + t;"
        "}"
        "document.onreadystatechange = function() {"
            "if (document.readyState !== 'complete') { return; }"
            "buildWdays();"
            "$('tan').value = todayStr();"
            "$('trt').onchange = function() {"
                "var iv = $('trt').value == '1';"
                "$('tint').style.display = iv ? '' : 'none';"
                "$('twdays').style.display = iv ? 'none' : '';"
            "};"
            "$('taddbtn').onclick = function() {"
                "var dm = 0;"
                "var ws = document.querySelectorAll('#twdays .wd');"
                "for (var i = 0; i < 7; i++) {"
                    "if (ws[i].classList.contains('on')) { dm |= (1 << i); }"
                "}"
                "var f = $('tfrom').value, t = $('tto').value;"
                "if (!f || !t || f >= t) { showState('Bitte g\\u00fcltige Zeiten angeben (Von < Bis)'); return; }"
                "if (scheds.length >= 8) { showState('Maximal 8 Zeitpl\\u00e4ne'); return; }"
                "scheds.push({"
                    "en: 1,"
                    "a: $('tdev').value,"
                    "rt: Number($('trt').value),"
                    "dm: dm || 127,"
                    "iv: Math.max(1, Number($('tiv').value) || 1),"
                    "an: $('tan').value || todayStr(),"
                    "f: f,"
                    "t: t,"
                    "md: $('tmd').value,"
                    "tp: Number($('ttp').value) || 21,"
                    "off: $('toff').checked ? 1 : 0"
                "});"
                "showState('');"
                "saveScheds();"
            "};"
            "fetch('/api/devices')"
                ".then(function(r) { return r.ok ? r.json() : []; })"
                ".then(function(d) { devices = (d && d.length !== undefined) ? d : []; fillDevs(); renderList(); })"
                ".catch(function() { fillDevs(); renderList(); });"
            "fetch('/api/schedules')"
                ".then(function(r) { return r.ok ? r.json() : []; })"
                ".then(function(d) { scheds = (d && d.length !== undefined) ? d : []; renderList(); })"
                ".catch(function() { renderList(); });"
        "}"
    "</script>";

