"""Generate the PWA app icons (192/512 px PNG) and embed them as PROGMEM
byte arrays in main/htmls/icons.h. Re-run after changing the design."""
from pathlib import Path

from PIL import Image, ImageDraw

REPO = Path(__file__).resolve().parent.parent
OUT_H = REPO / "main" / "htmls" / "icons.h"


def make_icon(size):
    s = size
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # rounded-square gradient background (blue -> cyan, diagonal)
    c1 = (37, 99, 235)   # --accent
    c2 = (6, 182, 212)   # --accent2
    grad = Image.new("RGBA", (s, s))
    gd = ImageDraw.Draw(grad)
    for y in range(s):
        for_x = y / (s - 1)
        r = int(c1[0] + (c2[0] - c1[0]) * for_x)
        g = int(c1[1] + (c2[1] - c1[1]) * for_x)
        b = int(c1[2] + (c2[2] - c1[2]) * for_x)
        gd.line([(0, y), (s, y)], fill=(r, g, b, 255))
    mask = Image.new("L", (s, s), 0)
    md = ImageDraw.Draw(mask)
    md.rounded_rectangle([0, 0, s - 1, s - 1], radius=int(s * 0.22), fill=255)
    img.paste(grad, (0, 0), mask)
    # white house outline
    w = max(2, int(s * 0.045))
    cx = s / 2
    top = s * 0.20
    roof_l = (s * 0.20, s * 0.46)
    roof_r = (s * 0.80, s * 0.46)
    d.line([roof_l, (cx, top), roof_r], fill="white", width=w, joint="curve")
    wall_t = s * 0.44
    wall_b = s * 0.78
    d.line([(s * 0.26, wall_t), (s * 0.26, wall_b), (s * 0.74, wall_b), (s * 0.74, wall_t)], fill="white", width=w, joint="curve")
    # snowflake inside (vertical + 2 diagonals)
    fc = (cx, s * 0.60)
    fr = s * 0.115
    for dx, dy in [(0, 1), (0.87, 0.5), (0.87, -0.5)]:
        d.line([(fc[0] - dx * fr, fc[1] - dy * fr), (fc[0] + dx * fr, fc[1] + dy * fr)], fill="white", width=w)
    return img


def to_c_array(name, data):
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        lines.append("  " + chunk + ",")
    lines.append("};")
    lines.append(f"const size_t {name}_len = {len(data)};")
    return "\n".join(lines)


parts = [
    "// generated by tools/gen_icons.py - do not edit by hand",
    "#pragma once",
    "#include <Arduino.h>",
    "",
]
for size in (192, 512):
    img = make_icon(size)
    tmp = REPO / "tools" / f"icon-{size}.png"
    img.save(tmp, "PNG", optimize=True)
    data = tmp.read_bytes()
    parts.append(to_c_array(f"icon_{size}_png", data))
    parts.append("")
    print(f"icon-{size}.png: {len(data)} bytes")

OUT_H.write_text("\n".join(parts), encoding="ascii")
print("written", OUT_H)
