"""Generate gzip-compressed PROGMEM blobs for the static web assets.

The big static assets (stylesheet + page scripts) are stored as C strings in
main/htmls/*.h so tools/webui_preview.py can assemble browser previews from
the sources. For the firmware they are compiled as gzip blobs instead and
served with "Content-Encoding: gzip": roughly a quarter of the flash and
transfer size, and connections close much sooner on the ESP8266.

Runs standalone (python tools/gen_static_gz.py) and as a PlatformIO
extra_script (pre:). The output main/htmls/static_gz.h is committed so
builds without PlatformIO (ESP-IDF/CMake) work unchanged; it is only
rewritten when the content actually changed to avoid needless recompiles.
"""
import gzip
import re
from pathlib import Path

try:
    REPO = Path(__file__).resolve().parent.parent
except NameError:
    # PlatformIO extra_script: SCons exec()s this file without __file__
    Import("env")  # noqa: F821
    REPO = Path(env["PROJECT_DIR"])  # noqa: F821
HTMLS = REPO / "main" / "htmls"
OUT = HTMLS / "static_gz.h"

# (C array name, source header, source C string variable)
ASSETS = [
    ("css_gz", "html_common.h", "html_css"),
    ("control_js_gz", "javascript_common.h", "control_js"),
    ("timers_js_gz", "javascript_common.h", "timers_js"),
    ("devices_js_gz", "javascript_common.h", "devices_js"),
]


def parse_c_string(path, wanted):
    """Concatenate the string literals of one PROGMEM variable (same
    algorithm as tools/webui_preview.py, so bytes match the compiled string)."""
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = "\n".join(l for l in text.splitlines() if not l.strip().startswith("#"))
    m = re.search(r"const char %s\[\] PROGMEM\s*=" % re.escape(wanted), text)
    if not m:
        raise SystemExit("variable %s not found in %s" % (wanted, path))
    i = m.end()
    parts = []
    in_str = False
    cur = []
    while i < len(text):
        c = text[i]
        if in_str:
            if c == "\\":
                nxt = text[i + 1]
                cur.append('"' if nxt == '"' else "\\" if nxt == "\\" else "\\" + nxt)
                i += 2
                continue
            if c == '"':
                in_str = False
                parts.append("".join(cur))
                cur = []
            else:
                cur.append(c)
        elif c == '"':
            in_str = True
        elif c == ";":
            break
        i += 1
    return "".join(parts)


def generate():
    lines = [
        "// AUTO-GENERATED by tools/gen_static_gz.py - DO NOT EDIT.",
        "// gzip blobs of the static assets; served with Content-Encoding: gzip.",
        "// The uncompressed source strings stay in their headers for the preview",
        "// tool and are compiled out via the KS_GZ_ASSETS guard.",
        "#define KS_GZ_ASSETS 1",
        "",
    ]
    for cname, fname, var in ASSETS:
        raw = parse_c_string(HTMLS / fname, var).encode("utf-8")
        gz = gzip.compress(raw, 9, mtime=0)  # mtime=0 -> deterministic output
        assert gzip.decompress(gz) == raw
        body = ",".join(str(b) for b in gz)
        lines.append("const uint8_t %s[] PROGMEM = {%s};" % (cname, body))
        lines.append("const unsigned int %s_len = %d;" % (cname, len(gz)))
        print("%s: %d -> %d bytes" % (var, len(raw), len(gz)))
    content = "\n".join(lines) + "\n"
    if OUT.exists() and OUT.read_text(encoding="utf-8") == content:
        print("static_gz.h unchanged")
        return
    OUT.write_text(content, encoding="utf-8", newline="\n")
    print("written", OUT)


generate()
